import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, collection, query, where, onSnapshot, doc, setDoc, updateDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const authBox=document.querySelector('#authBox'),consoleEl=document.querySelector('#console'),statusEl=document.querySelector('#authStatus'),logoutBtn=document.querySelector('#logout');
let unsubscribers=[];
document.querySelector('#login').onclick=async()=>{statusEl.textContent='Signing in…';try{await signInWithEmailAndPassword(auth,document.querySelector('#email').value.trim(),document.querySelector('#password').value);statusEl.textContent='';}catch{statusEl.textContent='Sign-in failed. Check credentials and moderator access.'}};
logoutBtn.onclick=()=>signOut(auth);

onAuthStateChanged(auth,user=>{unsubscribers.forEach(fn=>fn());unsubscribers=[];if(!user){authBox.classList.remove('hidden');consoleEl.classList.add('hidden');logoutBtn.classList.add('hidden');return}authBox.classList.add('hidden');consoleEl.classList.remove('hidden');logoutBtn.classList.remove('hidden');watchQueue('reports','new','reports','reportCount',renderReport);watchQueue('jobSubmissions','pending','jobSubmissions','jobCount',renderJob);watchQueue('businessSubmissions','pending','businessSubmissions','businessCount',renderBusiness)});
function watchQueue(collectionName,statusValue,targetId,countId,renderer){const q=query(collection(db,collectionName),where('status','==',statusValue));const unsub=onSnapshot(q,snap=>{document.querySelector('#'+countId).textContent=`${snap.size} pending`;const target=document.querySelector('#'+targetId);target.innerHTML='';if(!snap.size){target.innerHTML='<div class="reportCard">Nothing pending.</div>';return}snap.forEach(d=>renderer(d.id,d.data(),target));},err=>{document.querySelector('#'+targetId).innerHTML='<div class="reportCard">Access denied. Confirm this user UID exists in the Firestore <code>moderators</code> collection and the latest rules are published.</div>';console.error(err)});unsubscribers.push(unsub)}
function card(target,html){const c=document.createElement('article');c.className='reportCard';c.innerHTML=html;target.appendChild(c);return c}
function renderReport(id,r,target){const c=card(target,`<small>${esc(r.category||'Other')} · ${esc(r.location||'Unknown location')}</small><h3>${esc(r.description||'')}</h3><div class="actions"><button class="approve">Approve to public map</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveIssue(id,r);c.querySelector('.reject').onclick=()=>reject('reports',id)}
async function approveIssue(id,r){const latitude=Number(prompt('Verified latitude:'));if(!Number.isFinite(latitude))return;const longitude=Number(prompt('Verified longitude:'));if(!Number.isFinite(longitude))return;await setDoc(doc(db,'publicIssues',id),{category:r.category||'Other',location:r.location||'',description:r.description||'',status:'verified',latitude,longitude,source:'moderated-resident-report',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'reports',id),{status:'verified',moderatedAt:serverTimestamp()})}
function renderJob(id,j,target){const c=card(target,`<small>${esc(j.employer||'')} · ${esc(j.location||'')}</small><h3>${esc(j.role||'Local job')}</h3><p>${esc(j.details||'')}</p><b>${esc(j.payRange||'')}</b><div class="actions"><button class="approve">Approve job</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveJob(id,j);c.querySelector('.reject').onclick=()=>reject('jobSubmissions',id)}
async function approveJob(id,j){await setDoc(doc(db,'jobs',id),{role:j.role||'',employer:j.employer||'',location:j.location||'',payRange:j.payRange||'',details:j.details||'',status:'approved',source:'moderated-employer-submission',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'jobSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
function renderBusiness(id,b,target){const c=card(target,`<small>${esc(b.category||'')} · ${esc(b.location||'')}</small><h3>${esc(b.name||'Local business')}</h3><p>${esc(b.description||'')}</p><b>${esc(b.contact||'')}</b><div class="actions"><button class="approve">Approve business</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveBusiness(id,b);c.querySelector('.reject').onclick=()=>reject('businessSubmissions',id)}
async function approveBusiness(id,b){await setDoc(doc(db,'businesses',id),{name:b.name||'',category:b.category||'',location:b.location||'',contact:b.contact||'',description:b.description||'',status:'approved',source:'moderated-business-submission',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'businessSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
async function reject(collectionName,id){if(!confirm('Reject this submission?'))return;await updateDoc(doc(db,collectionName,id),{status:'rejected',moderatedAt:serverTimestamp()})}
function esc(v){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
