import { auth, db } from './firebase-platform.js';
import { signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js';
import { collection, query, where, onSnapshot, doc, setDoc, updateDoc, serverTimestamp, getDoc } from 'https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js';

const authBox=document.querySelector('#authBox'),consoleEl=document.querySelector('#console'),logoutBtn=document.querySelector('#logout');
let unsubscribers=[];
logoutBtn?.addEventListener('click',async()=>{await signOut(auth);location.replace('./government-login.html')});
onAuthStateChanged(auth,async user=>{unsubscribers.forEach(fn=>fn());unsubscribers=[];if(!user){location.replace('./government-login.html');return}try{const access=await getDoc(doc(db,'moderators',user.uid));if(!access.exists()){await signOut(auth);location.replace('./government-login.html?denied=1');return}authBox?.classList.add('hidden');consoleEl?.classList.remove('hidden');logoutBtn?.classList.remove('hidden');installMarketQueues();watchQueue('reports','new','reports','reportCount',renderReport);watchQueue('jobSubmissions','pending','jobSubmissions','jobCount',renderJob);watchQueue('businessSubmissions','pending','businessSubmissions','businessCount',renderBusiness);watchQueue('businessOwnershipSubmissions','pending','businessClaims','businessClaimCount',renderBusinessClaim);watchQueue('marketplaceProductSubmissions','pending','marketplaceProducts','marketplaceProductCount',renderProduct);watchQueue('deliveryPartnerSubmissions','pending','deliveryPartners','deliveryPartnerCount',renderDeliveryPartner)}catch(e){console.error(e);await signOut(auth);location.replace('./government-login.html?denied=1')}});
function watchQueue(collectionName,statusValue,targetId,countId,renderer){const q=query(collection(db,collectionName),where('status','==',statusValue));const unsub=onSnapshot(q,snap=>{document.querySelector('#'+countId).textContent=`${snap.size} pending`;const target=document.querySelector('#'+targetId);target.innerHTML='';if(!snap.size){target.innerHTML='<div class="reportCard">Nothing pending.</div>';return}snap.forEach(d=>renderer(d.id,d.data(),target));},err=>{document.querySelector('#'+targetId).innerHTML='<div class="reportCard">This account cannot open this queue.</div>';console.error(err)});unsubscribers.push(unsub)}
function card(target,html){const c=document.createElement('article');c.className='reportCard';c.innerHTML=html;target.appendChild(c);return c}
function renderReport(id,r,target){const c=card(target,`<small>${esc(r.category||'Other')} · ${esc(r.location||'Unknown location')}</small><h3>${esc(r.description||'')}</h3><div class="actions"><button class="approve">Approve to public map</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveIssue(id,r);c.querySelector('.reject').onclick=()=>reject('reports',id)}
async function approveIssue(id,r){const latitude=Number(prompt('Verified latitude:'));if(!Number.isFinite(latitude))return;const longitude=Number(prompt('Verified longitude:'));if(!Number.isFinite(longitude))return;await setDoc(doc(db,'publicIssues',id),{category:r.category||'Other',location:r.location||'',description:r.description||'',status:'verified',latitude,longitude,source:'moderated-resident-report',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'reports',id),{status:'verified',moderatedAt:serverTimestamp()})}
function renderJob(id,j,target){const c=card(target,`<small>${esc(j.employer||'')} · ${esc(j.location||'')}</small><h3>${esc(j.role||'Local job')}</h3><p>${esc(j.details||'')}</p><b>${esc(j.payRange||'')}</b><div class="actions"><button class="approve">Approve job</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveJob(id,j);c.querySelector('.reject').onclick=()=>reject('jobSubmissions',id)}
async function approveJob(id,j){await setDoc(doc(db,'jobs',id),{role:j.role||'',employer:j.employer||'',location:j.location||'',payRange:j.payRange||'',details:j.details||'',status:'approved',source:'moderated-employer-submission',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'jobSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
function renderBusiness(id,b,target){const c=card(target,`<small>${esc(b.category||'')} · ${esc(b.location||'')}</small><h3>${esc(b.name||'Local business')}</h3><p>${esc(b.description||'')}</p><b>${esc(b.contact||'')}</b><div class="actions"><button class="approve">Approve business</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveBusiness(id,b);c.querySelector('.reject').onclick=()=>reject('businessSubmissions',id)}
async function approveBusiness(id,b){await setDoc(doc(db,'businesses',id),{name:b.name||'',category:b.category||'',location:b.location||'',contact:b.contact||'',description:b.description||'',status:'approved',source:'moderated-business-submission',verifiedAt:serverTimestamp()});if(b.ownerUid)await setDoc(doc(db,'businessOwners',id),{ownerUid:b.ownerUid,name:b.name||'',location:b.location||'',verified:true,verifiedAt:serverTimestamp()});await updateDoc(doc(db,'businessSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
function installMarketQueues(){for(const [title,countId,listId] of [['Business ownership verification','businessClaimCount','businessClaims'],['Marketplace product submissions','marketplaceProductCount','marketplaceProducts'],['Independent delivery partner applications','deliveryPartnerCount','deliveryPartners']]){if(document.getElementById(listId))continue;const section=document.createElement('section');section.className='queue';section.innerHTML=`<div class="adminTop"><h3>${title}</h3><b id="${countId}">0 pending</b></div><div id="${listId}" class="adminGrid"></div>`;consoleEl.append(section)}}
async function renderBusinessClaim(id,c,target){const profile=await getDoc(doc(db,'businesses',c.businessId));const business=profile.exists()?profile.data().name||'Local business':'Listing unavailable';const cardEl=card(target,`<small>Ownership request · ${esc(business)}</small><h3>Applicant contact: ${esc(c.applicantPhone||'')}</h3><p>${esc(c.evidenceNote||'')}</p><div class="actions"><button class="approve">Verify ownership</button><button class="reject">Reject</button></div>`);cardEl.querySelector('.approve').onclick=()=>approveBusinessClaim(id,c);cardEl.querySelector('.reject').onclick=()=>reject('businessOwnershipSubmissions',id)}
async function approveBusinessClaim(id,c){if(!confirm('Have you contacted the business and verified that this applicant is authorized to manage its listing?'))return;const [ownerSnap,businessSnap]=await Promise.all([getDoc(doc(db,'businessOwners',c.businessId)),getDoc(doc(db,'businesses',c.businessId))]);if(ownerSnap.exists()){alert('This business already has a verified owner. Handle this as a manual ownership change.');return}if(!businessSnap.exists()||businessSnap.data().status!=='approved'){alert('This listing is no longer approved.');return}const b=businessSnap.data();await setDoc(doc(db,'businessOwners',c.businessId),{ownerUid:c.ownerUid,name:b.name||'',location:b.location||'',verified:true,verifiedAt:serverTimestamp()});await updateDoc(doc(db,'businessOwnershipSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
function renderProduct(id,p,target){const c=card(target,`<small>${esc(p.category||'')} · ${esc(p.location||'')}</small><h3>${esc(p.name||'Local product')}</h3><p>${esc(p.businessName||'')} · ₹${Number(p.price||0).toLocaleString('en-IN')} ${esc(p.unit||'')}</p><p>${esc(p.description||'')}</p><b>WhatsApp: ${esc(p.whatsapp||'')}</b><div class="actions"><button class="approve">Publish listing</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveProduct(id,p);c.querySelector('.reject').onclick=()=>reject('marketplaceProductSubmissions',id)}
async function approveProduct(id,p){const listing={businessId:p.businessId||'',businessName:p.businessName||'',location:p.location||'',name:p.name||'',category:p.category||'services',price:Number(p.price||0),unit:p.unit||'',description:p.description||'',whatsapp:p.whatsapp||'',status:'approved',verifiedAt:serverTimestamp()};await setDoc(doc(db,'marketplaceProducts',id),listing);await updateDoc(doc(db,'marketplaceProductSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
function renderDeliveryPartner(id,p,target){const c=card(target,`<small>${esc(p.vehicle||'')} · ${esc(p.coverageArea||'')}</small><h3>${esc(p.displayName||'Delivery partner')}</h3><p>Starting fee: ${Number(p.startingFee||0)?`₹${Number(p.startingFee).toLocaleString('en-IN')}`:'agreed directly'}</p><b>WhatsApp: ${esc(p.whatsapp||'')} · public contact consent: ${p.publicContactConsent?'yes':'no'}</b><div class="actions"><button class="approve">Approve public listing</button><button class="reject">Reject</button></div>`);c.querySelector('.approve').onclick=()=>approveDeliveryPartner(id,p);c.querySelector('.reject').onclick=()=>reject('deliveryPartnerSubmissions',id)}
async function approveDeliveryPartner(id,p){if(!p.publicContactConsent){alert('Public contact permission is missing. Do not publish this applicant.');return}await setDoc(doc(db,'localDeliveryPartners',id),{displayName:p.displayName||'',whatsapp:p.whatsapp||'',vehicle:p.vehicle||'',coverageArea:p.coverageArea||'',startingFee:Number(p.startingFee||0),status:'approved',verifiedAt:serverTimestamp()});await updateDoc(doc(db,'deliveryPartnerSubmissions',id),{status:'approved',moderatedAt:serverTimestamp()})}
async function reject(collectionName,id){if(!confirm('Reject this submission?'))return;await updateDoc(doc(db,collectionName,id),{status:'rejected',moderatedAt:serverTimestamp()})}
function esc(v){return String(v).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
