const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const L={
 en:{code:'EN',name:'English',hero:'What can Almora help you with?',sub:'One simple place for travel, services, jobs, health, education, tourism and everyday life across Almora.',ask:'Ask AI ↑',placeholder:'Ask anything about Almora…',nav:['News','Sports','Jobs','Directory','Videos','Culture'],report:'Report issue',explore:'Explore',signin:'Sign in',chips:['Hospital','Transport','Gov help','Jobs','Culture','Wildlife'],pulse:['Town help, all in one place','Trusted local information','Live weather','Online & ready'],today:'Today in Almora',doNow:'Do something now.',move:'Move through Almora.',find:'Find what matters.',notices:'Important updates for your day.',map:'Explore Almora on the map.',culture:'Culture is infrastructure too.',services:'Everyday life, routed.',trust:'Trust is visible.',urgent:'Important numbers.',missions:'AI aimed at actual problems.',newsTitle:'Important news, not noise.',newsIntro:'Innovation, policy, jobs, infrastructure and major developments affecting Almora or Uttarakhand.',sportsTitle:'Train where champions began.',sportsIntro:'Prominent Almora athletes, public sports infrastructure and local fitness options in one place.',videos:'Watch Almora',directorySearch:'Search hospital, college, electricity, office, shop…',menuTitle:'Explore Almora',resident:'Resident',business:'Business',government:'Public services',close:'Close',language:'Language',reportMenu:'Report a town problem',footer:'AI-powered local help for Almora.'},
 hi:{code:'हिं',name:'हिन्दी',hero:'अल्मोड़ा आपकी कैसे मदद कर सकता है?',sub:'यात्रा, सेवाएँ, रोज़गार, स्वास्थ्य, शिक्षा, पर्यटन और रोज़मर्रा की ज़रूरतें — सब एक जगह।',ask:'AI से पूछें ↑',placeholder:'अल्मोड़ा के बारे में कुछ भी पूछें…',nav:['समाचार','खेल','रोज़गार','डायरेक्टरी','वीडियो','संस्कृति'],report:'समस्या बताएँ',explore:'खोजें',signin:'लॉग इन',chips:['अस्पताल','यातायात','सरकारी मदद','रोज़गार','संस्कृति','वन्यजीव'],pulse:['शहर की मदद, एक जगह','भरोसेमंद स्थानीय जानकारी','आज का मौसम','ऑनलाइन और तैयार'],today:'आज का अल्मोड़ा',doNow:'अभी क्या करना है?',move:'अल्मोड़ा में आसानी से चलें।',find:'ज़रूरी जगह जल्दी खोजें।',notices:'आज के महत्वपूर्ण अपडेट।',map:'नक्शे पर अल्मोड़ा देखें।',culture:'संस्कृति भी हमारी ताकत है।',services:'रोज़मर्रा की मदद, सीधे रास्ते से।',trust:'जानकारी का भरोसा साफ़ दिखे।',urgent:'ज़रूरी नंबर।',missions:'असली समस्याओं पर AI की मदद।',newsTitle:'ज़रूरी खबरें, बिना शोर के।',newsIntro:'नवाचार, नीति, रोज़गार, बुनियादी ढाँचा और अल्मोड़ा या उत्तराखंड को प्रभावित करने वाली बड़ी खबरें।',sportsTitle:'जहाँ चैंपियन शुरू हुए, वहीं से ट्रेन करें।',sportsIntro:'अल्मोड़ा के प्रमुख खिलाड़ी, खेल सुविधाएँ और स्थानीय फिटनेस विकल्प एक जगह।',videos:'अल्मोड़ा देखें',directorySearch:'अस्पताल, कॉलेज, बिजली, दफ्तर, दुकान खोजें…',menuTitle:'अल्मोड़ा खोजें',resident:'निवासी',business:'व्यवसाय',government:'सरकारी सेवाएँ',close:'बंद करें',language:'भाषा',reportMenu:'शहर की समस्या बताएँ',footer:'अल्मोड़ा के लिए AI आधारित स्थानीय मदद।'},
 kfy:{code:'कुम',name:'कुमाऊँनी',hero:'अल्माड़ कसिक मदद कर सकूं?',sub:'सफर, सेवा, रोजगार, इलाज, पढ़ाई, घूमण-फिरण अर रोजमर्रा की जरूरत — सब एकै ठौर।',ask:'AI लै पुछौ ↑',placeholder:'अल्माड़ का बारे में कै बात पुछौ…',nav:['खबर','खेल','रोजगार','ठौर-ठिकाण','वीडियो','संस्कृति'],report:'दिक्कत बतौ',explore:'खोजौ',signin:'लॉग इन',chips:['अस्पताल','सफर','सरकारी मदद','रोजगार','संस्कृति','जंगली जानवर'],pulse:['नगर की मदद एकै ठौर','भरोसै की स्थानीय जानकारी','आज को मौसम','ऑनलाइन अर तैयार'],today:'आज को अल्माड़',doNow:'अब कै करण छ?',move:'अल्माड़ में सफर आसान बनौ।',find:'जरूरी ठौर जल्दी खोजौ।',notices:'आज की जरूरी खबर-बात।',map:'नक्शा में अल्माड़ देखौ।',culture:'संस्कृति हमार ताकत छ।',services:'रोजमर्रा की मदद, सीधो रास्तो।',trust:'जानकारी को भरोसो साफ दिखौ।',urgent:'जरूरी नंबर।',missions:'असली दिक्कतन में AI की मदद।',newsTitle:'जरूरी खबर, बेकार शोर बिना।',newsIntro:'नई खोज, नीति, रोजगार, सड़क-सुविधा अर अल्माड़-उत्तराखंड की बड़ी बातन पर ध्यान।',sportsTitle:'जां चैंपियन शुरू भया, वैं खेलौ-सीखौ।',sportsIntro:'अल्माड़ का खिलाड़ी, खेल सुविधा अर फिटनेस विकल्प एकै ठौर।',videos:'अल्माड़ देखौ',directorySearch:'अस्पताल, कॉलेज, बिजली, दफ्तर, दुकान खोजौ…',menuTitle:'अल्माड़ खोजौ',resident:'रैबार/निवासी',business:'कारोबार',government:'सरकारी सेवा',close:'बंद',language:'भाषा',reportMenu:'नगर की दिक्कत बतौ',footer:'अल्माड़ खातिर AI वाली स्थानीय मदद।'}
};
let lang=localStorage.getItem('almoraLang')||'en';
function setText(sel,text){const el=$(sel);if(el&&text)el.textContent=text}
function translateStatic(t){
 setText('.hero h1',t.hero);setText('.hero .sub',t.sub);setText('#ask',t.ask);if($('#prompt'))$('#prompt').placeholder=t.placeholder;
 const nav=$$('header nav > a').filter(a=>!a.classList.contains('identityLogin'));nav.slice(0,6).forEach((a,i)=>{if(t.nav[i])a.textContent=t.nav[i]});setText('#reportTop',t.report);setText('#identityLogin',t.signin);setText('#publicMenuButton .menuWord',t.explore);
 $$('.chips button').slice(0,6).forEach((b,i)=>{if(t.chips[i]){const emoji=(b.textContent.match(/^\s*[^\p{L}\p{N}]*/u)||[''])[0];b.textContent=`${emoji}${t.chips[i]}`}});
 const pulse=$$('.pulse b');pulse.slice(0,4).forEach((b,i)=>{if(t.pulse[i]&&i!==2)b.textContent=t.pulse[i]});
 setText('.townNow .kicker',t.today);setText('.townNow .glassPanel:nth-child(2) h3',t.doNow);
 setText('#transport .sectionHead h2',t.move);setText('#directory .sectionHead h2',t.find);setText('#notices .sectionHead h2',t.notices);setText('#map-section .sectionHead h2',t.map);setText('#culture .sectionHead h2',t.culture);setText('#services .sectionHead h2',t.services);setText('#missions .sectionHead h2',t.missions);
 const sectionHeads=$$('.sectionHead h2');sectionHeads.forEach(h=>{if(h.textContent.trim()==='Trust is visible.')h.textContent=t.trust;if(h.textContent.trim()==='Important numbers.')h.textContent=t.urgent});
 if($('#directorySearch'))$('#directorySearch').placeholder=t.directorySearch;const foot=$('footer .trust');if(foot)foot.textContent=t.footer;
}
function translateDynamic(t){
 setText('#news .newsTop h2',t.newsTitle);const np=$('#news .newsTop p');if(np)np.textContent=t.newsIntro;setText('#sports .sportsTop h2',t.sportsTitle);const sp=$('#sports .sportsTop p');if(sp)sp.textContent=t.sportsIntro;setText('#videos .kicker',t.videos);
 setText('#publicMenuDrawer .publicMenuHead h2',t.menuTitle);setText('#publicMenuDrawer .menuIdentity a:nth-child(1) b',t.resident);setText('#publicMenuDrawer .menuIdentity a:nth-child(2) b',t.business);setText('#publicMenuDrawer .menuIdentity a:nth-child(3) b',t.government);setText('#menuReport',`＋ ${t.reportMenu}`);const close=$('#publicMenuClose');if(close)close.setAttribute('aria-label',t.close);
 const reportTitle=$('#reportDialog h2');if(reportTitle)reportTitle.textContent=lang==='en'?'What needs attention?':lang==='hi'?'किस बात पर ध्यान चाहिए?':'कै दिक्कत छ?';
}
function ensureToggle(){const nav=$('header nav');if(!nav)return;let b=$('#languageToggle');if(!b){b=document.createElement('button');b.id='languageToggle';b.className='languageToggle';b.type='button';nav.insertBefore(b,nav.firstChild)}b.textContent=L[lang].code;b.title='English / हिन्दी / कुमाऊँनी';b.setAttribute('aria-label',`${L[lang].name} — tap to change language`);b.onclick=()=>{const order=['en','hi','kfy'];lang=order[(order.indexOf(lang)+1)%order.length];apply()}}
function apply(){const t=L[lang]||L.en;localStorage.setItem('almoraLang',lang);document.documentElement.lang=lang==='kfy'?'kfy':lang;ensureToggle();$('#languageToggle').textContent=t.code;translateStatic(t);translateDynamic(t);window.dispatchEvent(new CustomEvent('almora:language',{detail:{lang}}))}
window.almoraI18n={setLanguage(code){if(L[code]){lang=code;apply()}},getLanguage(){return lang},apply};
apply();setTimeout(apply,350);setTimeout(apply,1200);setTimeout(apply,2600);
