import {founderProfile,founderSupport} from './data/founder-profile.js';
const impactCss=document.createElement('link');impactCss.rel='stylesheet';impactCss.href='./impact.css';document.head.appendChild(impactCss);

const actionSection=document.createElement('section');
actionSection.id='action-hubs';actionSection.className='section';
actionSection.innerHTML=`<div class="sectionHead"><div><span>HIGH-IMPACT HELP</span><h2>Jobs, health and accountable government.</h2><p>Fast paths to verified services, with AI helping explain the next step instead of replacing the responsible institution.</p></div></div><div class="impactGrid">
<article class="impactCard reveal"><span class="founderBadge">💼 JOBS</span><h3>Get work, not just listings.</h3><p>Use Almora.ai's local jobs marketplace, your private skills profile and official Uttarakhand employment channels together.</p><div class="impactActions"><a class="primary" href="./jobs.html">Local jobs</a><a href="https://rojgar.uk.gov.in/" target="_blank" rel="noopener">Employment Dept ↗</a><a href="https://ukpsc.gov.in/" target="_blank" rel="noopener">UKPSC ↗</a><a href="https://sssc.uk.gov.in/" target="_blank" rel="noopener">UKSSSC ↗</a></div></article>
<article class="impactCard reveal"><span class="founderBadge">✚ HEALTH</span><h3>One-tap care navigation.</h3><p>Find Almora hospitals, call Uttarakhand's 24×7 health helpline, use telemedicine, or reach emergency transport.</p><div class="impactActions"><a class="primary" href="tel:104">Call 104</a><a href="tel:108">Emergency 108</a><a href="https://esanjeevani.mohfw.gov.in/" target="_blank" rel="noopener">eSanjeevani ↗</a><button data-health-ai>Ask health AI</button></div><div class="warningBox">Almora.ai provides navigation and general information, not diagnosis. For emergencies use the appropriate emergency service.</div></article>
<article class="impactCard reveal"><span class="founderBadge">◇ INTEGRITY</span><h3>Report a governance problem safely.</h3><p>Organise facts, dates, documents and the responsible department; then use an official grievance, vigilance or RTI channel.</p><div class="impactActions"><a class="primary" href="https://cmhelpline.uk.gov.in/" target="_blank" rel="noopener">CM Helpline 1905 ↗</a><a href="https://vigilance.uk.gov.in/" target="_blank" rel="noopener">Vigilance ↗</a><a href="https://rtionline.uk.gov.in/" target="_blank" rel="noopener">RTI ↗</a><button data-integrity-ai>Prepare my case</button></div><div class="warningBox">Unverified allegations are never published as facts. Almora.ai helps preserve evidence and route complaints; accountable authorities determine wrongdoing.</div></article></div></section>`;

const integrity=document.createElement('section');integrity.className='section';integrity.id='integrity';integrity.innerHTML=`<div class="integrityCard reveal"><span class="kicker">EVIDENCE-FIRST INTEGRITY WORKFLOW</span><h3>From frustration to an actionable record.</h3><div class="integritySteps"><div><b>1 · Capture</b><span>Date, place, service, amount/request and what occurred.</span></div><div><b>2 · Preserve</b><span>Keep receipts, screenshots, letters and reference numbers privately.</span></div><div><b>3 · Route</b><span>Choose grievance, vigilance, RTI, consumer or department channel.</span></div><div><b>4 · Track</b><span>Record acknowledgement and resolution status without public accusations.</span></div></div></div>`;

const founder=document.createElement('section');founder.className='section';founder.id='about-founder';founder.innerHTML=`<div class="sectionHead"><div><span>BUILDING ALMORA NOW</span><h2>Founder spotlight.</h2><p>This contemporary builder profile is separate from the historical figures section and is sourced from the founder's public profiles.</p></div></div><div class="founderWrap"><article class="founderCard reveal"><span class="founderBadge">आ · FOUNDER</span><h3>${founderProfile.name}</h3><p><b>${founderProfile.role}</b><br>${founderProfile.location}</p><p>${founderProfile.summary}</p><div class="founderFacts">${founderProfile.facts.map(x=>`<div class="founderFact">${x}</div>`).join('')}</div><div class="founderLinks">${founderProfile.links.map(x=>`<a href="${x.url}" target="_blank" rel="noopener">${x.label} ↗</a>`).join('')}</div><div class="microDisclosure">${founderProfile.sourceNote}</div></article><aside class="supportBox reveal"><span class="kicker">SUPPORT THE FOUNDER</span><h3>Help fund independent building.</h3><p>If Almora.ai, Roamwise or Mohit's creative/technology work is useful to you, you can choose to support him personally.</p><div class="impactActions">${founderSupport.enabled?`<a class="primary" href="${founderSupport.url}" target="_blank" rel="noopener">${founderSupport.label}</a>`:`<button class="primary" disabled>Support link awaiting verified payment details</button>`}</div><p class="microDisclosure">${founderSupport.disclosure}</p></aside></div>`;

const sourceAnchor=document.querySelector('#missions')||document.querySelector('footer');
sourceAnchor?.parentNode?.insertBefore(actionSection,sourceAnchor);
sourceAnchor?.parentNode?.insertBefore(integrity,sourceAnchor);
sourceAnchor?.parentNode?.insertBefore(founder,sourceAnchor);

function askAI(text){const p=document.querySelector('#prompt');if(!p)return;p.value=text;window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>document.querySelector('#ask')?.click(),450)}
document.querySelector('[data-health-ai]')?.addEventListener('click',()=>askAI('Help me navigate healthcare in Almora. Ask what kind of care I need, my broad location and whether it is urgent; use verified facilities and official health services only.'));
document.querySelector('[data-integrity-ai]')?.addEventListener('click',()=>askAI('Help me document and route a government service or corruption concern. Do not accuse anyone as fact. Ask for the department, date, broad location, evidence I have, and desired resolution; suggest the appropriate official grievance, vigilance or RTI route.'));
