import {watchCollection,firebaseReady} from './firebase-client.js';
const anchor=document.querySelector('#app-coverage')||document.querySelector('#discover');
const news=document.createElement('section');news.id='daily-news';news.className='section';news.innerHTML=`<div class="sectionHead"><div><span>ALMORA DAILY</span><h2>News without the noise.</h2><p>A lightweight daily feed refreshed by GitHub Actions. News is labelled by publisher and is not treated as an official government fact unless the source itself is official.</p></div></div><div id="newsGrid" class="directoryGrid"><article class="placeCard">Loading daily feed…</article></div>`;anchor?.parentNode?.insertBefore(news,anchor.nextSibling);
fetch('./data/news.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{const root=document.querySelector('#newsGrid');root.innerHTML=(d.items||[]).slice(0,9).map(x=>`<article class="placeCard reveal"><span class="trustBadge">${x.tag||'News'}</span><h3>${x.title}</h3><p>${x.source||'Publisher'} · ${x.published||''}</p><div class="actions"><a href="${x.url}" target="_blank" rel="noopener">Read source ↗</a></div></article>`).join('')||'<article class="placeCard">No fresh items in the current feed.</article>'}).catch(()=>{document.querySelector('#newsGrid').innerHTML='<article class="placeCard">Daily feed temporarily unavailable.</article>'});

const heat=document.createElement('section');heat.className='section';heat.id='hotspot-map';heat.innerHTML=`<div class="sectionHead"><div><span>MODERATED HEATMAP</span><h2>Where pressure is building.</h2><p>This map plots only public, moderator-approved issue coordinates. Marker size grows when multiple issues cluster nearby; reporter identities are never shown.</p></div></div><div class="mapShell"><div id="heatMap" style="height:420px;border-radius:24px"></div><div id="heatStatus" class="mapNote">Waiting for verified public issues…</div></div>`;news.parentNode?.insertBefore(heat,news.nextSibling);
if(window.L){const m=L.map('heatMap',{zoomControl:false}).setView([29.5892,79.6467],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(m);let layers=[];if(firebaseReady)watchCollection('publicIssues',rows=>{layers.forEach(x=>m.removeLayer(x));layers=[];const pts=rows.map(x=>({x,lat:Number(x.lat??x.latitude??x.location?.lat),lng:Number(x.lng??x.longitude??x.location?.lng)})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));for(const p of pts){const nearby=pts.filter(q=>Math.abs(q.lat-p.lat)<.012&&Math.abs(q.lng-p.lng)<.012).length;const c=L.circleMarker([p.lat,p.lng],{radius:Math.min(22,7+nearby*3),weight:1,fillOpacity:Math.min(.85,.35+nearby*.12)}).bindPopup(`<b>${String(p.x.title||p.x.category||'Verified issue').replace(/[<>]/g,'')}</b><br>${String(p.x.status||'Public moderated record').replace(/[<>]/g,'')}`);c.addTo(m);layers.push(c)}document.querySelector('#heatStatus').textContent=pts.length?`${pts.length} geocoded verified public issue signal${pts.length===1?'':'s'} · identities hidden`:'No geocoded verified public issues yet.'},()=>{document.querySelector('#heatStatus').textContent='Could not load verified issue signals.'});}

const services=document.createElement('section');services.className='section';services.id='local-help';services.innerHTML=`<div class="sectionHead"><div><span>LOCAL HELP NETWORK</span><h2>From “I need someone” to a trusted match.</h2><p>Electrician, plumber, cleaner, cook, driver, home help, medicine pickup and local delivery — requests stay private while moderators build the approved provider network.</p></div><div><a class="primaryLink" href="./services.html">Request local help →</a></div></div>`;heat.parentNode?.insertBefore(services,heat.nextSibling);
