import {temples,touristPlaces,people,digitalServices,droneVideos} from './data/experience-data.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

function media(x,label='Almora'){if(x.image)return `<div class="mediaImage photo"><img src="${x.image}" alt="${label}" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.hidden=true;this.parentElement.classList.add('generative');this.parentElement.innerHTML='<span>आ</span>'"></div>`;return `<div class="mediaImage generative"><span>आ</span><small>Illustrative visual</small></div>`}
const section=document.createElement('section');section.id='discover';section.className='section';section.innerHTML=`<div class="sectionHead"><div><span>ALMORA, SEEN + HEARD</span><h2>A living multimedia atlas.</h2><p>Temples, nature, cultural memory, innovators and cinematic views — with provenance shown wherever possible.</p></div></div>
<div class="experienceTabs"><button class="active" data-exp="temples">Temples</button><button data-exp="places">Places</button><button data-exp="people">People</button><button data-exp="video">Drone films</button></div><div id="experienceGrid" class="experienceGrid"></div>`;
const insertBefore=document.querySelector('#culture')||document.querySelector('#services');insertBefore?.parentNode?.insertBefore(section,insertBefore);
function renderExperience(type='temples'){const root=$('#experienceGrid');if(!root)return;if(type==='temples')root.innerHTML=temples.map(x=>`<article class="experienceCard reveal">${media(x,x.name)}<div class="experienceBody"><small>${x.kind}</small><h3>${x.name}</h3><p>${x.detail}</p><div class="actions"><a href="${maps(x.name+' Almora')}" target="_blank" rel="noopener">Navigate ↗</a><a href="${x.sourceUrl}" target="_blank" rel="noopener">Source</a></div></div></article>`).join('');if(type==='places')root.innerHTML=touristPlaces.map(x=>`<article class="experienceCard reveal"><div class="mediaImage generative landscape"><span>✦</span><small>${x.type}</small></div><div class="experienceBody"><small>${x.type}</small><h3>${x.name}</h3><p>${x.detail}</p><div class="actions"><a href="${maps(x.name+' Almora')}" target="_blank" rel="noopener">Navigate ↗</a><a href="${x.sourceUrl}" target="_blank" rel="noopener">Source</a></div></div></article>`).join('');if(type==='people')root.innerHTML=people.map(x=>`<article class="experienceCard reveal"><div class="mediaImage generative portrait"><span>${x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</span><small>${x.tag}</small></div><div class="experienceBody"><small>${x.tag}</small><h3>${x.name}</h3><p><b>${x.relation}</b><br>${x.detail}</p>${x.sourceUrl?`<div class="actions"><a href="${x.sourceUrl}" target="_blank" rel="noopener">Source ↗</a></div>`:''}</div></article>`).join('');if(type==='video')root.innerHTML=droneVideos.map(v=>`<article class="videoCard reveal"><a class="videoPoster" href="https://www.youtube.com/watch?v=${v.youtubeId}" target="_blank" rel="noopener" aria-label="Play ${v.title} on YouTube"><img src="https://i.ytimg.com/vi/${v.youtubeId}/hqdefault.jpg" alt="${v.title}" loading="lazy" decoding="async"><span class="playButton">▶</span><small>PLAY DRONE FILM</small></a><h3>${v.title}</h3><p>${v.credit} · ${v.note}</p></article>`).join('');$$('.reveal',root).forEach(x=>requestAnimationFrame(()=>x.classList.add('in')))}
$$('.experienceTabs button').forEach(b=>b.onclick=()=>{$$('.experienceTabs button').forEach(x=>x.classList.toggle('active',x===b));renderExperience(b.dataset.exp)});renderExperience();

const live=document.createElement('section');live.id='live-intelligence';live.className='section';live.innerHTML=`<div class="sectionHead"><div><span>LIVE INTELLIGENCE</span><h2>Weather, traffic and crowd signals.</h2><p>Weather is fetched live. Traffic opens Google Maps' live traffic/navigation experience. The heatmap uses only moderated public Almora.ai issue signals, not private user data.</p></div></div><div class="liveIntelGrid"><article class="glassPanel"><span class="kicker">WEATHER NOW</span><h3 id="weatherRich">Loading…</h3><p id="weatherDetail">Open-Meteo live conditions for Almora.</p></article><article class="glassPanel"><span class="kicker">LIVE TRAFFIC</span><h3>See congestion before you move.</h3><p>Google Maps can show traffic delays, crashes, construction and road closures where data exists.</p><a class="primaryLink" href="https://www.google.com/maps/@29.5892,79.6467,13z/data=!5m1!1e1" target="_blank" rel="noopener">Open live traffic ↗</a></article><article class="glassPanel"><span class="kicker">ALMORA HEATMAP</span><h3>Community pressure points.</h3><p>Use the live map's moderated reports to identify repeated road, wildlife, transport and service hotspots without exposing reporters.</p><button id="heatmapAsk">Ask AI about hotspots</button></article></div>`;section.parentNode?.insertBefore(live,section.nextSibling);
async function richWeather(){try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=29.5892&longitude=79.6467&current=temperature_2m,apparent_temperature,precipitation,rain,wind_speed_10m,weather_code&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=Asia%2FKolkata');const d=await r.json(),c=d.current;$('#weatherRich').textContent=`${Math.round(c.temperature_2m)}°C · feels ${Math.round(c.apparent_temperature)}°C`;$('#weatherDetail').textContent=`Wind ${Math.round(c.wind_speed_10m)} km/h · rain ${c.rain||0} mm · today ${Math.round(d.daily.temperature_2m_min[0])}–${Math.round(d.daily.temperature_2m_max[0])}°C · precipitation chance ${d.daily.precipitation_probability_max[0]}%`;}catch{$('#weatherRich').textContent='Weather temporarily unavailable'}}richWeather();$('#heatmapAsk')?.addEventListener('click',()=>{const p=$('#prompt');if(p){p.value='Summarise verified public issue hotspots in Almora from the current Firestore context. Separate observed data from inference and do not expose private reporters.';window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#ask')?.click(),400)}});

const apps=document.createElement('section');apps.id='app-coverage';apps.className='section';apps.innerHTML=`<div class="sectionHead"><div><span>DIGITAL SERVICES</span><h2>What works in Almora?</h2><p>Coverage is source-checked. Unknown services stay on a watchlist instead of being guessed unavailable.</p></div></div><div class="appCoverageGrid">${digitalServices.map(x=>`<article class="appCard ${x.status}"><span>${x.status==='verified'?'● Verified in Almora':'◌ Coverage watch'}</span><h3>${x.name}</h3><p><b>${x.category}</b><br>${x.detail}</p>${x.url?`<a href="${x.url}" target="_blank" rel="noopener">Open service ↗</a>`:''}</article>`).join('')}</div>`;live.parentNode?.insertBefore(apps,live.nextSibling);
import('./live-extras.js').catch(console.error);

for(const href of ['./news-sports.css','./ux-upgrade.css']){const link=document.createElement('link');link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
import('./news-sports.js').catch(console.error);
import('./ux-upgrade.js').catch(console.error);
