const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const maps=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

const news=[
 {cat:'innovation',date:'8 Aug 2026',source:'The Economic Times',title:'Almora innovator test-flies a single-seat “flying car” prototype',summary:'Ravi Tamta of Kaflikhan, Almora demonstrated the HAPIDA SKYNeX prototype, an electric aerial vehicle concept aimed at cutting travel times in difficult hill terrain.',url:'https://m.economictimes.com/news/new-updates/this-uttarakhand-youth-built-a-flying-car-watch-it-take-off-in-almora/articleshow/133027113.cms',featured:true},
 {cat:'policy',date:'8 Aug 2026',source:'Times of India',title:'Uttarakhand Forward 2.0 maps a development path to 2047',summary:'The state roadmap highlights infrastructure, clean energy, education, tourism, sustainability and governance — all directly relevant to the future of hill districts such as Almora.',url:'https://timesofindia.indiatimes.com/india/uttarakhand-forward-2-0-manoj-pant-maps-out-development-roadmap-to-2047/articleshow/133029230.cms'},
 {cat:'jobs',date:'Open through 15 Aug 2026',source:'UKSSSC',title:'Uttarakhand recruitment open for accountant and assistant-accountant roles',summary:'UKSSSC advertisement 79/UKSSSC/2026 lists direct recruitment for accountant, assistant accountant, office assistant (accounts) and related posts. Almora.ai links candidates to the official application source.',url:'https://sssc.uk.gov.in/'},
 {cat:'policy',date:'8 Aug 2026',source:'Navbharat Times',title:'State cabinet approves sports, eco-tourism and worker-welfare measures',summary:'Recent cabinet decisions include 122 posts for Uttarakhand Sports University along with measures spanning eco-tourism, labour welfare and development.',url:'https://navbharattimes.indiatimes.com/state/uttarakhand/dehradun/uttarakhand-cabinet-meeting-15-big-decisions-dhami-cow-scheme-ganga-expressway-highcourt-land/articleshow/133034497.cms'},
 {cat:'civic',date:'Valid through 17 Aug 2026',source:'District Almora',title:'Monsoon Road Opening SOP 2026–27 remains an active official notice',summary:'The district administration has published its monsoon road-opening SOP. This is the kind of high-importance local operational update Almora.ai should surface ahead of routine news.',url:'https://almora.nic.in/notice_category/announcements/'},
 {cat:'jobs',date:'Updated 24 Jul 2026',source:'UKSSSC',title:'Official Uttarakhand jobs tracker remains active',summary:'UKSSSC is publishing recruitment notices, exam schedules and application links. The Almora feed prioritises official job opportunities useful to local residents over generic job-content sites.',url:'https://sssc.uk.gov.in/'}
];

const athletes=[
 {name:'Lakshya Sen',tag:'Badminton · Olympian',relation:'Born in Almora',detail:'Commonwealth Games champion, World Championships medallist and Arjuna Award recipient. His rise from Almora’s badminton culture is one of the town’s strongest modern sports stories.',url:'https://commons.wikimedia.org/wiki/Category:Lakshya_Sen',img:'https://commons.wikimedia.org/wiki/Special:Redirect/file/Lakshya%20Sen%20(cropped).jpg?width=900',featured:true},
 {name:'Ekta Bisht',tag:'Cricket · India',relation:'Born in Almora',detail:'Left-arm spinner for India and the first Uttarakhand cricketer to represent the country. She became the first Indian woman to take a T20I hat-trick.',url:'https://sports.ndtv.com/cricket/players/50721-ekta-bisht-playerprofile'},
 {name:'Chirag Sen',tag:'Badminton',relation:'Almora badminton family',detail:'International badminton player from the Sen family; part of the wider badminton ecosystem that has made Almora unusually productive in the sport.',url:'https://sports.uk.gov.in/'}
];

const fitness=[
 {type:'Gym',name:'ELITE FITNESS STUDIO ALMORA',area:'Near Simkhani Ground, Khatyari',rating:'5.0 · 9 reviews',phone:'+918937098233'},
 {type:'Gym',name:'Synergy Fitness Centre Kholta Almora',area:'Lower Mall Road, Kholta',rating:'4.9 · 7 reviews',phone:'+919410184222'},
 {type:'Fitness · Zumba · Yoga',name:'Natraj Dance & Zumba Fitness Institute Almora',area:'L.R. Shah Road, Dharanaula',rating:'4.9 · 76 reviews',phone:'+919410133009'},
 {type:'Stadium',name:'Hemvati Nandan Bahuguna Stadium Almora',area:'Khatyari, Almora',rating:'4.3 · 1,380 reviews'},
];

const infra=[
 {name:'Hemvati Nandan Bahuguna Sports Stadium',detail:'Official Uttarakhand sports listings identify H.N. Bahuguna Sports Stadium in Almora. State and district competitions including badminton, boxing and cross-country have been scheduled here.',url:'https://sports.uk.gov.in/%E0%A4%96%E0%A5%87%E0%A4%B2-%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A5%87%E0%A4%A1%E0%A4%BF%E0%A4%AF%E0%A4%AE/'},
 {name:'Almora district competition calendar',detail:'The state sports department publishes a district calendar covering badminton and other competitions at H.N. Bahuguna Sports Stadium, useful for athletes, parents and coaches.',url:'https://sports.uk.gov.in/%E0%A4%85%E0%A4%B2%E0%A5%8D%E0%A4%AE%E0%A5%8B%E0%A4%A1%E0%A4%BC%E0%A4%BE-%E0%A4%96%E0%A5%87%E0%A4%B2-%E0%A4%95%E0%A5%88%E0%A4%B2%E0%A5%87%E0%A4%82%E0%A4%A1%E0%A4%B0-2025-26/'}
];

const newsSection=document.createElement('section');
newsSection.id='news';newsSection.className='section';
newsSection.innerHTML=`<div class="newsHero reveal"><div class="newsTop"><div><span class="kicker">ALMORA NOW</span><h2>Important news, not noise.</h2><p>Innovation, policy, jobs, infrastructure and major developments affecting Almora or Uttarakhand. Routine crime and low-value incidents are intentionally excluded unless they become major state or national stories.</p></div><div class="newsStamp"><i></i> CURATED · 9 AUG 2026</div></div><div class="newsFilters"><button class="active" data-news="all">All important</button><button data-news="innovation">Innovation</button><button data-news="policy">Policy</button><button data-news="jobs">Jobs</button><button data-news="civic">Civic</button></div><div id="newsGrid" class="newsGrid"></div><div class="newsPolicy"><b>Editorial rule:</b><span>Prioritise information that can change opportunity, mobility, safety, infrastructure or public life. Crime is not a default content category.</span></div></div>`;
const pulse=document.querySelector('.pulse');pulse?.parentNode?.insertBefore(newsSection,pulse.nextSibling);
function renderNews(cat='all'){const rows=news.filter(x=>cat==='all'||x.cat===cat);$('#newsGrid').innerHTML=rows.map((x,i)=>`<article class="newsCard ${x.featured&&cat==='all'?'featured':''}"><div class="newsMeta"><span>${x.cat}</span><span>${x.date}</span></div><h3>${x.title}</h3><p>${x.summary}</p><a href="${x.url}" target="_blank" rel="noopener">Read at ${x.source} ↗</a></article>`).join('')}
$$('.newsFilters button',newsSection).forEach(b=>b.onclick=()=>{$$('.newsFilters button',newsSection).forEach(x=>x.classList.toggle('active',x===b));renderNews(b.dataset.news)});renderNews();

const sports=document.createElement('section');sports.id='sports';sports.className='section';sports.innerHTML=`<div class="sportsHero reveal"><div class="sportsTop"><div><span class="kicker">SPORTS + FITNESS</span><h2>Train where champions began.</h2><p>Prominent Almora athletes, public sports infrastructure and local fitness options in one searchable layer.</p></div></div><div class="sportsStars">${athletes.map(x=>`<article class="athleteCard ${x.featured?'featured':''}">${x.img?`<div class="athleteVisual" style="background-image:url('${x.img}')"></div>`:`<div class="athleteFallback">${x.name.split(' ').map(w=>w[0]).join('').slice(0,2)}</div>`}<div class="athleteBody"><small>${x.tag}</small><h3>${x.name}</h3><p><b>${x.relation}</b><br>${x.detail}</p><a href="${x.url}" target="_blank" rel="noopener">Profile / source ↗</a></div></article>`).join('')}</div><div class="fitnessWrap"><div class="fitnessHead"><div><span class="kicker">LOCAL FITNESS DIRECTORY</span><h3>Gyms, fitness & sports infrastructure.</h3><p>Current discoverable listings; businesses can be added or corrected as the directory grows.</p></div></div><div class="fitnessFilters"><button class="active" data-fit="all">All</button><button data-fit="gym">Gyms</button><button data-fit="fitness">Fitness</button><button data-fit="stadium">Stadium</button></div><div id="fitnessGrid" class="fitnessGrid"></div><div class="sportsInfra">${infra.map(x=>`<article class="infraCard"><span class="kicker">OFFICIAL SPORTS INFRASTRUCTURE</span><h4>${x.name}</h4><p>${x.detail}</p><a href="${x.url}" target="_blank" rel="noopener">Official source ↗</a></article>`).join('')}</div></div><div class="mediaSpotlight" id="videos"><div class="mediaSpotlightHead"><div><span class="kicker">WATCH ALMORA</span><h3>Videos that actually play here.</h3></div><a href="./docs.html" style="color:var(--lime);text-decoration:none;font-size:12px">Open docs →</a></div><div class="videoWall"><div><div class="videoEmbed"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/_giPAFAkjw8" title="Almora from Above" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="videoInfo"><b>Almora from Above</b><small>RPS · 2026 · YouTube</small></div></div><div><div class="videoEmbed"><iframe loading="lazy" src="https://www.youtube-nocookie.com/embed/KHn01Wakd6k" title="Aerial view of Jageshwar Dham" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><div class="videoInfo"><b>Jageshwar Dham from the air</b><small>WildFilmsIndia · YouTube</small></div></div></div></div></div>`;
const culture=document.querySelector('#culture');culture?.parentNode?.insertBefore(sports,culture);
function renderFitness(type='all'){const rows=fitness.filter(x=>type==='all'||x.type.toLowerCase().includes(type));$('#fitnessGrid').innerHTML=rows.map(x=>`<article class="fitnessCard"><span class="type">${x.type.toUpperCase()}</span><h4>${x.name}</h4><p>${x.area}</p><div class="rating">★ ${x.rating||'Listing'}</div><div class="actions"><a href="${maps(x.name+' Almora Uttarakhand')}" target="_blank" rel="noopener">Map ↗</a>${x.phone?`<a href="tel:${x.phone}">Call</a>`:''}</div></article>`).join('')}
$$('.fitnessFilters button',sports).forEach(b=>b.onclick=()=>{$$('.fitnessFilters button',sports).forEach(x=>x.classList.toggle('active',x===b));renderFitness(b.dataset.fit)});renderFitness();
