import {directory,culture,figures,officialLinks,emergency,liveNotices} from './data/almora-knowledge.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const mapUrl=q=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;
const dirUrl=q=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`;

const categories={all:'All',health:'Health',education:'Education',government:'Gov',utility:'Utilities',transport:'Transport',shopping:'Shops'};
let activeCategory='all';
function renderDirectory(){const q=($('#directorySearch')?.value||'').toLowerCase();const root=$('#directoryGrid');if(!root)return;const rows=directory.filter(x=>(activeCategory==='all'||x.category===activeCategory)&&`${x.name} ${x.area} ${x.category}`.toLowerCase().includes(q));root.innerHTML=rows.map(x=>`<article class="placeCard reveal"><span class="trustBadge ${x.trust==='official'?'official':''}">${x.trust==='official'?'● Official source':'◌ Directory listing'}</span><h3>${x.name}</h3><p>${x.area}${x.phone?`<br><b>${x.phone}</b>`:''}</p><div class="actions"><a href="${dirUrl(x.query)}" target="_blank" rel="noopener">Navigate ↗</a>${x.phone?`<a href="tel:${x.phone.replace(/[^0-9+]/g,'')}">Call</a>`:''}${x.sourceUrl?`<a href="${x.sourceUrl}" target="_blank" rel="noopener">Source</a>`:''}</div></article>`).join('')||'<article class="placeCard"><h3>No match</h3><p>Ask Almora AI and we’ll route the request.</p></article>';activateReveal();}
function buildDirectory(){const filters=$('#directoryFilters');if(!filters)return;filters.innerHTML=Object.entries(categories).map(([k,v])=>`<button data-cat="${k}" class="${k==='all'?'active':''}">${v}</button>`).join('');filters.onclick=e=>{const b=e.target.closest('button');if(!b)return;activeCategory=b.dataset.cat;$$('#directoryFilters button').forEach(x=>x.classList.toggle('active',x===b));renderDirectory()};$('#directorySearch').addEventListener('input',renderDirectory);renderDirectory();}

const modeInfo={
 bus:{title:'Public bus',desc:'Start with Almora Bus Terminal. For intercity journeys, verify the latest Uttarakhand Transport/UTC timetable before departure.',dest:'Almora Bus Terminal',prompt:'Help me travel by public bus from Almora. Ask my destination and give verified-first options.'},
 taxi:{title:'Shared / private taxi',desc:'Dharanaula is a common local transport node. Compare availability and price before committing; directory listings are not government verification.',dest:'Taxi Services Dharanaula Almora',prompt:'Help me find a taxi or shared taxi from Almora. Ask where I am going, timing and group size.'},
 walk:{title:'Walk / local',desc:'For nearby Almora destinations, use live navigation and account for steep terrain, stairs and weather.',dest:'Almora Uttarakhand',prompt:'Help me plan a safe walking route in Almora. Ask my start and destination.'},
 drive:{title:'Private vehicle',desc:'Use live navigation and check verified road/access reports before longer hill-road travel.',dest:'Almora Uttarakhand',prompt:'Help me plan a private vehicle route from Almora and check road-access considerations.'}
};
function setMode(mode){const x=modeInfo[mode];if(!x)return;$$('.modeBtn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#routeTitle').textContent=x.title;$('#routeDesc').textContent=x.desc;$('#routeNavigate').href=dirUrl(x.dest);$('#routeAsk').dataset.q=x.prompt;}
function buildTransport(){$$('.modeBtn').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode('bus');$('#routeAsk')?.addEventListener('click',()=>{const p=$('#prompt');if(p){p.value=$('#routeAsk').dataset.q;p.scrollIntoView({behavior:'smooth',block:'center'});$('#ask')?.click();}})}

function renderCulture(){const cal=$('#calendarList'),fig=$('#figureList');if(cal)cal.innerHTML=culture.map(x=>`<div class="calendarItem reveal"><div class="dateTile">${x.when.split('·')[0].trim()}</div><div><h4>${x.name}</h4><p>${x.type} · ${x.detail}</p>${x.sourceUrl?`<a href="${x.sourceUrl}" target="_blank" rel="noopener">Official context ↗</a>`:''}</div></div>`).join('');if(fig)fig.innerHTML=figures.map(x=>`<div class="figureItem reveal"><div class="monogram">${x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div><h4>${x.name}</h4><p><b>${x.relation}</b> · ${x.tag}<br>${x.detail}</p>${x.sourceUrl?`<a href="${x.sourceUrl}" target="_blank" rel="noopener">Source ↗</a>`:''}</div></div>`).join('');}
function renderSources(){const s=$('#sourceWall');if(s)s.innerHTML=officialLinks.map(x=>`<a class="reveal" href="${x.url}" target="_blank" rel="noopener"><b>${x.label} ↗</b><span>${x.detail}</span></a>`).join('');const e=$('#emergencyStrip');if(e)e.innerHTML=emergency.map(x=>`<a href="tel:${x.phone}"><small>${x.label}</small><b>${x.phone}</b></a>`).join('');}
function renderNotices(){const n=$('#noticeGrid');if(!n)return;n.innerHTML=liveNotices.map(x=>`<article class="placeCard reveal"><span class="trustBadge official">● ${x.status}</span><h3>${x.title}</h3><p>${x.summary}</p><small>${x.start} → ${x.end}</small><div class="actions"><a href="${x.url}" target="_blank" rel="noopener">Open official notice ↗</a><button class="noticeAsk" data-q="Explain the official Almora notice: ${x.title}. Tell me what it means for a resident or traveller, and do not infer live road closures unless verified.">Ask AI</button></div></article>`).join('');$$('.noticeAsk').forEach(b=>b.onclick=()=>{const p=$('#prompt');if(!p)return;p.value=b.dataset.q;window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#ask')?.click(),450)});activateReveal();}
function activateReveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal:not(.in)').forEach(x=>io.observe(x));}

function quickActions(){$$('.quickDock button').forEach(b=>b.onclick=()=>{const target=$(b.dataset.target);if(target)target.scrollIntoView({behavior:'smooth'});else if(b.dataset.q){const p=$('#prompt');if(p){p.value=b.dataset.q;window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#ask')?.click(),450)}}});$$('.oneTap').forEach(b=>b.onclick=()=>{if(b.dataset.target)$(b.dataset.target)?.scrollIntoView({behavior:'smooth'});else if(b.dataset.q){const p=$('#prompt');if(p){p.value=b.dataset.q;window.scrollTo({top:0,behavior:'smooth'});setTimeout(()=>$('#ask')?.click(),450)}}});}

function updateToday(){const d=new Date();const el=$('#todayDate');if(el)el.textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(d);const hour=d.getHours();const g=$('#dayGreeting');if(g)g.textContent=hour<12?'Good morning, Almora.':hour<17?'Good afternoon, Almora.':'Good evening, Almora.';}

buildDirectory();buildTransport();renderCulture();renderSources();renderNotices();quickActions();updateToday();activateReveal();
