import {directory,culture,figures,officialLinks,emergency,liveNotices} from './data/almora-knowledge.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const dirUrl=q=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(q)}`;
const categories={all:'All',health:'Health',education:'Education',government:'Gov',utility:'Utilities',transport:'Transport',shopping:'Shops'};let activeCategory='all';
function renderDirectory(){const root=$('#directoryGrid');if(!root)return;const q=($('#directorySearch')?.value||'').toLowerCase();const rows=directory.filter(x=>(activeCategory==='all'||x.category===activeCategory)&&`${x.name} ${x.area} ${x.category}`.toLowerCase().includes(q));root.innerHTML=rows.map(x=>`<article class="placeCard reveal"><span class="trustBadge ${x.trust==='official'?'official':''}">${x.trust==='official'?'● Verified':'◌ Local listing'}</span><h3>${x.name}</h3><p>${x.area}${x.phone?`<br><b>${x.phone}</b>`:''}</p><div class="actions"><a href="${dirUrl(x.query)}" target="_blank" rel="noopener">Navigate ↗</a>${x.phone?`<a href="tel:${x.phone.replace(/[^0-9+]/g,'')}">Call</a>`:''}${x.sourceUrl?`<a href="${x.sourceUrl}" target="_blank" rel="noopener">Details</a>`:''}</div></article>`).join('')||'<article class="placeCard"><h3>No match</h3><p>Try another search or ask Almora AI.</p></article>';activateReveal()}
function buildDirectory(){const f=$('#directoryFilters');if(!f)return;f.innerHTML=Object.entries(categories).map(([k,v])=>`<button data-cat="${k}" class="${k==='all'?'active':''}">${v}</button>`).join('');f.onclick=e=>{const b=e.target.closest('button');if(!b)return;activeCategory=b.dataset.cat;$$('#directoryFilters button').forEach(x=>x.classList.toggle('active',x===b));renderDirectory()};$('#directorySearch')?.addEventListener('input',renderDirectory);renderDirectory()}
const modeInfo={bus:{title:'Public bus',desc:'Start with Almora Bus Terminal and confirm the latest departure information.',dest:'Almora Bus Terminal'},taxi:{title:'Shared / private taxi',desc:'Find a taxi or shared taxi and confirm the fare before travel.',dest:'Taxi Services Dharanaula Almora'},walk:{title:'Walk / local',desc:'Use navigation and account for steep terrain, stairs and weather.',dest:'Almora Uttarakhand'},drive:{title:'Private vehicle',desc:'Use navigation and check road conditions before longer hill-road travel.',dest:'Almora Uttarakhand'}};
function buildTransport(){$$('.modeBtn').forEach(b=>b.onclick=()=>{const x=modeInfo[b.dataset.mode];$$('.modeBtn').forEach(z=>z.classList.toggle('active',z===b));$('#routeTitle').textContent=x.title;$('#routeDesc').textContent=x.desc;$('#routeNavigate').href=dirUrl(x.dest)});$('.modeBtn')?.click()}
function renderCulture(){if($('#calendarList'))$('#calendarList').innerHTML=culture.map(x=>`<div class="calendarItem reveal"><div class="dateTile">${x.when.split('·')[0].trim()}</div><div><h4>${x.name}</h4><p>${x.type} · ${x.detail}</p></div></div>`).join('');if($('#figureList'))$('#figureList').innerHTML=figures.map(x=>`<div class="figureItem reveal"><div class="monogram">${x.name.split(' ').map(w=>w[0]).slice(0,2).join('')}</div><div><h4>${x.name}</h4><p><b>${x.relation}</b> · ${x.tag}<br>${x.detail}</p></div></div>`).join('')}
function renderSources(){if($('#sourceWall'))$('#sourceWall').innerHTML=officialLinks.map(x=>`<a href="${x.url}" target="_blank" rel="noopener"><b>${x.label} ↗</b><span>${x.detail}</span></a>`).join('');if($('#emergencyStrip'))$('#emergencyStrip').innerHTML=emergency.map(x=>`<a href="tel:${x.phone}"><small>${x.label}</small><b>${x.phone}</b></a>`).join('')}
function renderNotices(){if($('#noticeGrid'))$('#noticeGrid').innerHTML=liveNotices.map(x=>`<article class="placeCard reveal"><span class="trustBadge official">● ${x.status}</span><h3>${x.title}</h3><p>${x.summary}</p><small>${x.start} → ${x.end}</small><div class="actions"><a href="${x.url}" target="_blank" rel="noopener">Read update ↗</a></div></article>`).join('')}
function activateReveal(){if(!('IntersectionObserver'in window)){$$('.reveal').forEach(x=>x.classList.add('in'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{rootMargin:'180px'});$$('.reveal:not(.in)').forEach(x=>io.observe(x))}
function friendlyCopy(){const pulse=$$('.pulse b');if(pulse[0])pulse[0].textContent='Town help, all in one place';if(pulse[1])pulse[1].textContent='Trusted local information';if(pulse[3])pulse[3].textContent='Online & ready';const mapP=$('#map-section .sectionHead p');if(mapP)mapP.textContent='Explore Almora, useful places and community updates on the map.'}
function installLanguage(){const nav=$('header nav');if(!nav||$('#languageToggle'))return;const b=document.createElement('button');b.id='languageToggle';b.className='languageToggle';b.type='button';nav.insertBefore(b,nav.firstChild);const langs=['en','hi','kfy'];let lang=localStorage.getItem('almoraLang')||'en';const text={en:{button:'EN',hero:'What can Almora help you with?',sub:'One simple place for travel, services, jobs, health, education, tourism and everyday life across Almora.',ask:'Ask AI ↑'},hi:{button:'हिं',hero:'अल्मोड़ा आपकी कैसे मदद कर सकता है?',sub:'यात्रा, सेवाएँ, रोज़गार, स्वास्थ्य, शिक्षा, पर्यटन और रोज़मर्रा की ज़रूरतें — सब एक जगह।',ask:'AI से पूछें ↑'},kfy:{button:'कुम',hero:'अल्माड़ कसिक मदद कर सकूं?',sub:'सफर, सेवा, रोजगार, इलाज, पढ़ाई, घूमण-फिरण अर रोजमर्रा की मदद — सब एकै ठौर।',ask:'AI लै पुछौ ↑'}};function apply(){const t=text[lang];b.textContent=t.button;const h=$('.hero h1');if(h)h.textContent=t.hero;const s=$('.hero .sub');if(s)s.textContent=t.sub;const a=$('#ask');if(a)a.textContent=t.ask;document.documentElement.lang=lang==='hi'?'hi':lang==='kfy'?'kfy':'en';localStorage.setItem('almoraLang',lang)}b.onclick=()=>{lang=langs[(langs.indexOf(lang)+1)%langs.length];apply()};b.title='English / हिन्दी / कुमाऊँनी';apply()}
function updateToday(){const d=new Date();const el=$('#todayDate');if(el)el.textContent=new Intl.DateTimeFormat('en-IN',{weekday:'long',day:'numeric',month:'long'}).format(d)}
try{buildDirectory();buildTransport();renderCulture();renderSources();renderNotices();updateToday();friendlyCopy();installLanguage();activateReveal()}catch(e){console.error('Almora UI',e)}
for(const href of ['./multimedia.css','./public-menu.css']){if(!document.querySelector(`link[href="${href}"]`)){const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}}
import('./multimedia.js').catch(console.error);
import('./public-menu.js').catch(console.error);
