import {firebaseReady,addTownReport} from './firebase-client.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];

function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2400)}

const nav=$('header nav');
if(nav){nav.innerHTML=`<div class="topNavMore"><a href="#news">News</a><a href="#sports">Sports</a><a href="./jobs.html">Jobs</a><a href="#directory">Directory</a><a href="#videos">Videos</a><a href="./docs.html">Docs</a></div><button id="reportTop">Report issue</button>`;}

const dialog=$('#reportDialog');
const types=[['🛣️','Road / access'],['🐒','Monkey / wildlife'],['🚌','Transport'],['🌾','Farming'],['🏥','Health access'],['🎓','Education'],['💰','Price / scam'],['🏛️','Public service'],['✦','Other']];
let report={category:'',location:'',description:''},step=1;
function reportMarkup(){return `<form method="dialog"><div class="reportShell"><div class="formGlow"></div><button class="close" value="cancel" aria-label="Close">×</button><span>REPORT TO ALMORA AI</span><h2 style="margin-bottom:4px">${step===1?'What needs attention?':step===2?'Where and what happened?':'Ready to send?'}</h2><div class="stepCaption"><span>STEP ${step} OF 3</span><span>${step===1?'Choose a route':step===2?'Add useful context':'Review privately'}</span></div><div class="reportProgress"><i class="${step>=1?'on':''}"></i><i class="${step>=2?'on':''}"></i><i class="${step>=3?'on':''}"></i></div>${step===1?`<div class="reportTypeGrid">${types.map(([icon,name])=>`<button type="button" class="reportType ${report.category===name?'selected':''}" data-report-type="${name}"><span>${icon}</span>${name}</button>`).join('')}</div>`:''}${step===2?`<div class="floatingField"><input id="modernLocation" placeholder=" " value="${report.location.replaceAll('"','&quot;')}"><label>Locality, village or landmark</label></div><button type="button" id="useMyLocation" style="margin-top:8px;border:0;background:transparent;color:var(--lime);padding:6px 0;cursor:pointer">◎ Use my approximate location</button><div class="floatingField"><textarea id="modernDescription" placeholder=" " rows="5">${report.description}</textarea><label>Describe what you observed</label></div><p class="privacy">Keep reports factual. Do not include Aadhaar numbers, medical records, passwords or unnecessary personal data.</p>`:''}${step===3?`<div class="reportReview"><small>CATEGORY</small><b>${report.category}</b><small>LOCATION</small><b>${report.location}</b><small>REPORT</small><b>${report.description}</b><small>PRIVACY</small><p>This enters the private moderation queue first. It is not automatically published as a verified town fact.</p></div>`:''}<div id="modernReportStatus" class="privacy"></div><div class="reportFoot">${step>1?'<button type="button" id="reportBack">← Back</button>':'<span></span>'}<button type="button" class="next" id="reportNext">${step===3?'Submit for review →':'Continue →'}</button></div></div></form>`}
function bindReport(){dialog.classList.add('reportModern');dialog.innerHTML=reportMarkup();$$('[data-report-type]',dialog).forEach(b=>b.onclick=()=>{report.category=b.dataset.reportType;$$('[data-report-type]',dialog).forEach(x=>x.classList.toggle('selected',x===b))});$('#reportBack',dialog)?.addEventListener('click',()=>{step--;bindReport()});$('#useMyLocation',dialog)?.addEventListener('click',()=>{if(!navigator.geolocation)return toast('Location is not supported here.');navigator.geolocation.getCurrentPosition(p=>{const value=`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`;$('#modernLocation',dialog).value=value;toast('Approximate location added.')},()=>toast('Location permission was not available.'))});$('#reportNext',dialog)?.addEventListener('click',async()=>{const status=$('#modernReportStatus',dialog);if(step===1){if(!report.category){status.textContent='Choose the closest category first.';return}step=2;bindReport();return}if(step===2){report.location=$('#modernLocation',dialog).value.trim();report.description=$('#modernDescription',dialog).value.trim();if(!report.location||report.description.length<8){status.textContent='Add a location and a little more detail so the report can be routed.';return}step=3;bindReport();return}const payload={...report,status:'new',source:'resident',createdAt:new Date().toISOString()};try{status.textContent='Sending securely…';if(firebaseReady){await addTownReport(payload);status.textContent='Submitted to the private moderation queue.'}else{const rows=JSON.parse(localStorage.getItem('almora_reports')||'[]');rows.push(payload);localStorage.setItem('almora_reports',JSON.stringify(rows));status.textContent='Saved on this device. Firebase is currently unavailable.'}setTimeout(()=>{dialog.close();step=1;report={category:'',location:'',description:''};bindReport();toast('Report received for review.')},900)}catch(e){console.error(e);status.textContent='Could not submit right now. Your text is still in the form.'}})}
bindReport();
function openReport(){step=1;bindReport();if(!dialog.open)dialog.showModal()}
$('#report')?.addEventListener('click',e=>{e.preventDefault();openReport()});$('#reportTop')?.addEventListener('click',openReport);$('#menuReport')?.addEventListener('click',()=>setTimeout(openReport,80));

const supportLink=$('.supportBox a.primary');
if(supportLink){const upi=supportLink.href;const upiId='coolmohit@ybl';const pay=document.createElement('dialog');pay.className='supportModal';const qr=`https://quickchart.io/qr?size=320&margin=1&text=${encodeURIComponent(upi)}`;pay.innerHTML=`<div class="supportInner"><div class="supportHead"><div><span class="kicker">SUPPORT ALMORA.AI</span><h2>Pay from any UPI app.</h2></div><button class="supportClose" aria-label="Close">×</button></div><div class="payGrid"><div class="payQr"><img src="${qr}" alt="UPI QR for ${upiId}"></div><div><div class="payUpi"><small>UPI ID</small><b>${upiId}</b></div><div class="payButtons"><button id="copyUpi">Copy UPI ID</button><a href="${upi}">Open UPI app</a></div></div></div><p class="payNote">Personal voluntary support for the founder. This is not a government fee, charity donation, investment, or payment for civic priority.</p></div>`;document.body.appendChild(pay);supportLink.href='#support';supportLink.removeAttribute('target');supportLink.onclick=e=>{e.preventDefault();pay.showModal()};$('.supportClose',pay).onclick=()=>pay.close();$('#copyUpi',pay).onclick=async()=>{try{await navigator.clipboard.writeText(upiId);toast('UPI ID copied.')}catch{toast(`UPI ID: ${upiId}`)}};pay.addEventListener('click',e=>{if(e.target===pay)pay.close()});}

const legacyReportButton=$('#report');if(legacyReportButton)legacyReportButton.onclick=null;
const oldMenuReport=$('#menuReport');if(oldMenuReport){const fresh=oldMenuReport.cloneNode(true);oldMenuReport.replaceWith(fresh);fresh.onclick=()=>{document.querySelector('#publicMenuClose')?.click();setTimeout(openReport,120)}}
