const CACHE_PREFIX='almora:runtime:';const ERROR_KEY='almora:runtime-errors';
function now(){return Date.now()}
function readCache(key,maxAge){try{const v=JSON.parse(localStorage.getItem(CACHE_PREFIX+key)||'null');if(!v)return null;if(maxAge&&now()-v.at>maxAge)return null;return v.value}catch{return null}}
function writeCache(key,value){try{localStorage.setItem(CACHE_PREFIX+key,JSON.stringify({at:now(),value}))}catch{}}
function recordError(error,context='runtime'){try{const items=JSON.parse(localStorage.getItem(ERROR_KEY)||'[]');items.unshift({at:new Date().toISOString(),context,message:String(error?.message||error).slice(0,240)});localStorage.setItem(ERROR_KEY,JSON.stringify(items.slice(0,20)))}catch{}}
function delay(ms){return new Promise(r=>setTimeout(r,ms))}
async function fetchWithTimeout(url,options={},timeout=6500){const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),timeout);try{return await fetch(url,{...options,signal:ctl.signal})}finally{clearTimeout(timer)}}
async function safeFetch(url,{timeout=6500,retries=1,method='GET',headers,body,cacheKey=url,maxAge=60*60*1000,allowStale=true,cache='no-store'}={}){let last;for(let attempt=0;attempt<=retries;attempt++){try{const response=await fetchWithTimeout(url,{method,headers,body,cache},timeout);if(!response.ok)throw new Error(`HTTP ${response.status} for ${url}`);return response}catch(error){last=error;if(attempt<retries)await delay(220*(attempt+1))}}recordError(last,`fetch:${url}`);if(method==='GET'&&allowStale){const cached=readCache(cacheKey,maxAge*8);if(cached!==null)return{ok:true,status:200,fromCache:true,json:async()=>cached,text:async()=>typeof cached==='string'?cached:JSON.stringify(cached)}}throw last}
async function safeJSON(url,options={}){const key=options.cacheKey||url;try{const response=await safeFetch(url,{...options,cacheKey:key});const value=await response.json();writeCache(key,value);return{value,source:response.fromCache?'stale-cache':'network'}}catch(error){const cached=readCache(key,options.maxAge?options.maxAge*8:8*60*60*1000);if(cached!==null)return{value:cached,source:'stale-cache'};recordError(error,`json:${url}`);return{value:options.fallback??null,source:'fallback',error}}}
async function race(primary,fallback,{timeout=7500}={}){let timer;try{return await Promise.race([Promise.resolve().then(primary),new Promise((_,reject)=>timer=setTimeout(()=>reject(new Error('operation timeout')),timeout))])}catch(error){recordError(error,'race');return typeof fallback==='function'?fallback(error):fallback}finally{clearTimeout(timer)}}
function installRuntime(){if(window.__ALMORA_RUNTIME__)return window.__ALMORA_RUNTIME__;const set=()=>document.documentElement.dataset.network=navigator.onLine?'online':'offline';set();addEventListener('online',set);addEventListener('offline',set);addEventListener('error',e=>recordError(e.error||e.message,'window'));addEventListener('unhandledrejection',e=>recordError(e.reason,'promise'));window.__ALMORA_RUNTIME__={safeFetch,safeJSON,race,readCache,writeCache,recordError};return window.__ALMORA_RUNTIME__}
export{safeFetch,safeJSON,race,readCache,writeCache,recordError,installRuntime};
