import{CULTURES,setCultureTheme,read}from'./theme-runtime.js';
const THEMES=CULTURES.map(([id,label])=>[id,label,`theme-${id}`]);
const controlCopy={
  en:{picker:'Cultural visual theme',current:'Cultural theme',option:'cultural theme',menu:'Cultural visual themes'},
  hi:{picker:'सांस्कृतिक दृश्य थीम',current:'सांस्कृतिक थीम',option:'सांस्कृतिक थीम',menu:'सांस्कृतिक दृश्य थीम विकल्प'},
  kfy:{picker:'सांस्कृतिक दृश्य थीम',current:'सांस्कृतिक थीम',option:'सांस्कृतिक थीम',menu:'सांस्कृतिक दृश्य थीम विकल्प'}
};
function language(){return document.querySelector('[data-lang].active')?.dataset.lang||localStorage.getItem('almoraLang')||document.documentElement.lang||'en'}
function applyCultureTheme(name){return setCultureTheme(name)}
function mountCultureTheme(){const host=document.querySelector('.topActions');if(!host||document.querySelector('.cultureThemePicker'))return;const wrap=document.createElement('div');wrap.className='cultureThemePicker';wrap.innerHTML=`<button type="button" id="cultureThemeBtn" aria-haspopup="menu" aria-controls="cultureThemeMenu" aria-expanded="false">✺</button>`;host.insertBefore(wrap,host.querySelector('.weatherTiny'));const main=wrap.querySelector('#cultureThemeBtn'),menu=document.createElement('div');menu.id='cultureThemeMenu';menu.className='cultureMenu';menu.setAttribute('role','menu');menu.innerHTML=CULTURES.map(([id,label])=>`<button type="button" role="menuitemradio" aria-checked="false" data-culture="${id}"><span class="cultureSwatch"></span><span>${label}</span></button>`).join('');document.body.appendChild(menu);const items=[...menu.querySelectorAll('[data-culture]')],labelOf=v=>CULTURES.find(x=>x[0]===v)?.[1]||'Aipan';const paint=()=>{const selected=document.documentElement.dataset.cultureTheme,label=labelOf(selected),text=controlCopy[language()]||controlCopy.en;main.title=`${text.current}: ${label}`;main.setAttribute('aria-label',`${text.picker}: ${label}`);menu.setAttribute('aria-label',text.menu);items.forEach(item=>{const itemLabel=labelOf(item.dataset.culture);item.setAttribute('aria-label',`${itemLabel} ${text.option}`);item.setAttribute('aria-checked',item.dataset.culture===selected?'true':'false')})};const close=(restoreFocus=false)=>{menu.classList.remove('open');main.setAttribute('aria-expanded','false');if(restoreFocus)main.focus()};paint();main.onclick=e=>{e.stopPropagation();const opening=!menu.classList.contains('open');close();if(opening){menu.classList.add('open');main.setAttribute('aria-expanded','true');(items.find(item=>item.getAttribute('aria-checked')==='true')||items[0])?.focus()}};items.forEach((b,index)=>{b.onclick=e=>{e.stopPropagation();applyCultureTheme(b.dataset.culture);paint();close(true)};b.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();close(true)}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const step=e.key==='ArrowDown'?1:-1;items[(index+step+items.length)%items.length]?.focus()}}});menu.onclick=e=>e.stopPropagation();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.classList.contains('open')){e.preventDefault();close(true)}});document.addEventListener('click',()=>close());addEventListener('resize',()=>close(),{passive:true});window.addEventListener('almora:language',paint)}
function initCultureTheme(){read();mountCultureTheme()}
export{initCultureTheme,applyCultureTheme,THEMES};
