import{setLang}from'./i18n.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const THEMES=[{id:'aipan',label:{en:'Aipan',hi:'ऐपण',kfy:'ऐपण'}},{id:'chholiya',label:{en:'Chholiya',hi:'छोलिया',kfy:'छोलिया'}},{id:'nanda-devi',label:{en:'Nanda Devi',hi:'नंदा देवी',kfy:'नंदा देवी'}},{id:'modern',label:{en:'Modern',hi:'मॉडर्न',kfy:'मॉडर्न'}}];
const HEROES=[{url:'./assets/generated/hero-aipan-girl.webp',label:{en:'Aipan heritage · Almora',hi:'ऐपण विरासत · अल्मोड़ा',kfy:'ऐपण विरासत · अल्माड़'}},{url:'./assets/generated/hero-connected-almora.webp',label:{en:'Connected Almora',hi:'जुड़ा अल्मोड़ा',kfy:'जुड़ अल्माड़'}},{url:'./assets/generated/almora-sunset.webp',label:{en:'Golden hour',hi:'सुनहरी शाम',kfy:'सुनौल बखत'}},{url:'./assets/generated/almora-twilight.webp',label:{en:'Twilight',hi:'सांझ',kfy:'संझ्याव'}},{url:'./assets/generated/hero-founder.webp',label:{en:'Built for Almora',hi:'अल्मोड़ा के लिए',kfy:'अल्माड़ खातिर'}}];
let heroIndex=0;const lang=()=>localStorage.getItem('almoraLang')||document.documentElement.lang||'en';
function applyTheme(id){const theme=THEMES.find(t=>t.id===id)||THEMES[0];document.documentElement.dataset.cultureTheme=theme.id;document.documentElement.dataset.theme=theme.id==='modern'?'modern':'heritage';localStorage.setItem('almoraCultureTheme',theme.id);localStorage.setItem('almoraTheme',document.documentElement.dataset.theme);const label=$('#themeLabel');if(label)label.textContent=theme.label[lang()]||theme.label.en}
function nextTheme(){const current=document.documentElement.dataset.cultureTheme||'aipan',i=THEMES.findIndex(t=>t.id===current);applyTheme(THEMES[(i+1)%THEMES.length].id)}
function toggleVisualMode(){const next=document.documentElement.dataset.theme==='heritage'?'modern':'heritage';document.documentElement.dataset.theme=next;localStorage.setItem('almoraTheme',next);const label=$('#themeLabel');if(label)label.textContent=next==='modern'?(lang()==='hi'?'मॉडर्न':lang()==='kfy'?'मॉडर्न':'Modern'):(lang()==='hi'?'विरासत':lang()==='kfy'?'विरासत':'Heritage')}
function showHero(index){heroIndex=(index+HEROES.length)%HEROES.length;const item=HEROES[heroIndex],photo=$('.heroPhoto');if(!photo)return;const img=new Image();img.onload=()=>{photo.style.opacity='.18';requestAnimationFrame(()=>{photo.style.backgroundImage=`url("${item.url}")`;photo.style.opacity='1';const lab=$('#heroArtLabel');if(lab)lab.textContent=item.label[lang()]||item.label.en})};img.onerror=()=>{photo.style.backgroundImage="url('./assets/generated/hero-aipan-girl.webp')"};img.src=item.url}
function ensureHeroNav(){const hero=$('.hero');if(!hero||$('.heroNav',hero))return;const nav=document.createElement('div');nav.className='heroNav';nav.innerHTML='<button type="button" aria-label="Previous hero">‹</button><button type="button" aria-label="Next hero">›</button>';const[prev,next]=nav.querySelectorAll('button');prev.onclick=()=>showHero(heroIndex-1);next.onclick=()=>showHero(heroIndex+1);hero.append(nav)}
function ensureEngineBridges(){const q=$('.quickActions');if(!q||$('[data-q*="official hospitals"]',q))return;const b=document.createElement('button');b.type='button';b.dataset.q='find official hospitals in Almora';b.innerHTML='<span>🏥</span><b data-i18n="hospitals">Hospitals</b>';b.addEventListener('click',()=>{const input=$('#askInput');if(input)input.value=b.dataset.q;$('#askForm')?.requestSubmit()});q.append(b)}
const copy={en:{local:'Live local desk',time:'Almora time',important:'Important contacts',officials:'Key officials',media:'News & media directory',openDirectory:'Open full directory →',source:'Official district source',updated:'Official contacts checked 10 Aug 2026',weatherUnavailable:'Live weather unavailable',aqi:'Air quality',sunrise:'Sunrise',sunset:'Sunset'},hi:{local:'लाइव स्थानीय डेस्क',time:'अल्मोड़ा समय',important:'ज़रूरी संपर्क',officials:'प्रमुख अधिकारी',media:'समाचार व मीडिया डायरेक्टरी',openDirectory:'पूरी डायरेक्टरी खोलें →',source:'आधिकारिक जिला स्रोत',updated:'आधिकारिक संपर्क 10 अगस्त 2026 को जाँचे गए',weatherUnavailable:'लाइव मौसम उपलब्ध नहीं',aqi:'वायु गुणवत्ता',sunrise:'सूर्योदय',sunset:'सूर्यास्त'},kfy:{local:'लाइव स्थानीय डेस्क',time:'अल्माड़ को बखत',important:'जरूरी संपर्क',officials:'मुख्य अधिकारी',media:'खबर अर मीडिया डायरेक्टरी',openDirectory:'पूरि डायरेक्टरी खोलौ →',source:'सरकारी जिला स्रोत',updated:'सरकारी संपर्क 10 अगस्त 2026 में जांचा',weatherUnavailable:'लाइव मौसम नि मिलो',aqi:'हवा की गुणवत्ता',sunrise:'सूरज उगण',sunset:'सूरज डूबण'}};const tr=k=>copy[lang()]?.[k]||copy.en[k]||k;
function tick(){const now=new Date(),locale=lang()==='en'?'en-IN':'hi-IN',t=new Intl.DateTimeFormat(locale,{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now),d=new Intl.DateTimeFormat(locale,{timeZone:'Asia/Kolkata',weekday:'short',day:'numeric',month:'short'}).format(now);if($('#liveClock'))$('#liveClock').textContent=t;if($('#liveDate'))$('#liveDate').textContent=d+' · IST'}
async function liveWeather(){try{const[wr,ar]=await Promise.all([fetch('https://api.open-meteo.com/v1/forecast?latitude=29.5892&longitude=79.6467&current=temperature_2m&daily=sunrise,sunset&timezone=Asia%2FKolkata&forecast_days=1'),fetch('https://air-quality-api.open-meteo.com/v1/air-quality?latitude=29.5892&longitude=79.6467&current=us_aqi&timezone=Asia%2FKolkata')]);if(!wr.ok)throw new Error('weather');const w=await wr.json(),a=ar.ok?await ar.json():null,n=Math.round(w.current.temperature_2m),sr=w.daily?.sunrise?.[0]?.split('T')[1]||'—',ss=w.daily?.sunset?.[0]?.split('T')[1]||'—',aqi=a?.current?.us_aqi;if($('#topTemp'))$('#topTemp').textContent=`${n}°C`;if($('#bigTemp'))$('#bigTemp').textContent=`${n}°C`;const sun=$$('.sunGrid b');if(sun[0])sun[0].textContent=sr;if(sun[1])sun[1].textContent=ss;if($('.aqi'))$('.aqi').textContent=Number.isFinite(aqi)?`AQI ${Math.round(aqi)} · live`:'AQI · unavailable';if($('#weatherLine'))$('#weatherLine').textContent=`${n}°C · ${tr('sunrise')} ${sr} · ${tr('sunset')} ${ss}`;if($('#aqiLine'))$('#aqiLine').textContent=Number.isFinite(aqi)?`${tr('aqi')}: ${Math.round(aqi)} (US AQI)`:tr('weatherUnavailable')}catch{if($('.aqi'))$('.aqi').textContent='AQI · unavailable';if($('#weatherLine'))$('#weatherLine').textContent=tr('weatherUnavailable')}}
function localize(){$$('[data-local-key]').forEach(el=>{el.textContent=tr(el.dataset.localKey)});const item=HEROES[heroIndex],lab=$('#heroArtLabel');if(lab)lab.textContent=item.label[lang()]||item.label.en;$$('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang()));tick()}
function install(){const savedCulture=localStorage.getItem('almoraCultureTheme')||'aipan',savedMode=localStorage.getItem('almoraTheme');applyTheme(savedCulture);if(savedMode)document.documentElement.dataset.theme=savedMode;const themeBtn=$('#themeBtn');if(themeBtn)themeBtn.onclick=toggleVisualMode;const cultureBtn=$('#cultureThemeBtn');if(cultureBtn)cultureBtn.addEventListener('dblclick',nextTheme);$$('[data-lang]').forEach(b=>b.onclick=()=>{setLang(b.dataset.lang);localize()});ensureHeroNav();ensureEngineBridges();showHero(0);tick();liveWeather();localize();setInterval(tick,1000);setInterval(()=>showHero(heroIndex+1),11000);setInterval(liveWeather,10*60*1000);window.addEventListener('almora:language',localize);window.addEventListener('resize',()=>{document.body.classList.toggle('compactViewport',innerWidth<901)},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
