import'./home-visuals.js';
import'./nav-router.js';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const copy={en:{local:'Live local desk',time:'Almora time',weather:'Live weather',important:'Important contacts',officials:'Key officials',media:'News & media directory',updated:'Official contacts checked 10 Aug 2026',disaster:'District Disaster Control Room',dm:'District Magistrate',source:'Official district source',openDirectory:'Open full directory →',weatherUnavailable:'Live weather unavailable',aqi:'Air quality',sunrise:'Sunrise',sunset:'Sunset'},hi:{local:'लाइव स्थानीय डेस्क',time:'अल्मोड़ा समय',weather:'लाइव मौसम',important:'ज़रूरी संपर्क',officials:'प्रमुख अधिकारी',media:'समाचार व मीडिया डायरेक्टरी',updated:'आधिकारिक संपर्क 10 अगस्त 2026 को जाँचे गए',disaster:'जिला आपदा नियंत्रण कक्ष',dm:'जिलाधिकारी',source:'आधिकारिक जिला स्रोत',openDirectory:'पूरी डायरेक्टरी खोलें →',weatherUnavailable:'लाइव मौसम उपलब्ध नहीं',aqi:'वायु गुणवत्ता',sunrise:'सूर्योदय',sunset:'सूर्यास्त'},kfy:{local:'लाइव स्थानीय डेस्क',time:'अल्माड़ को बखत',weather:'लाइव मौसम',important:'जरूरी संपर्क',officials:'मुख्य अधिकारी',media:'खबर अर मीडिया डायरेक्टरी',updated:'सरकारी संपर्क 10 अगस्त 2026 में जांच्या',disaster:'जिला आपदा कंट्रोल रूम',dm:'जिलाधिकारी',source:'सरकारी जिला स्रोत',openDirectory:'पूरि डायरेक्टरी खोलौ →',weatherUnavailable:'लाइव मौसम नि मिलो',aqi:'हवा की गुणवत्ता',sunrise:'सूरज उगण',sunset:'सूरज डूबण'}};
function lang(){return $('[data-lang].active')?.dataset.lang||document.documentElement.lang||'en'}function tr(k){return copy[lang()]?.[k]||copy.en[k]||k}
function tick(){const now=new Date();const locale=lang()==='en'?'en-IN':'hi-IN';const time=new Intl.DateTimeFormat(locale,{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(now);const date=new Intl.DateTimeFormat(locale,{timeZone:'Asia/Kolkata',weekday:'short',day:'numeric',month:'short'}).format(now);if($('#liveClock'))$('#liveClock').textContent=time;if($('#liveDate'))$('#liveDate').textContent=date+' · IST'}
async function liveWeather(){try{const[wr,ar]=await Promise.all([fetch('https://api.open-meteo.com/v1/forecast?latitude=29.5892&longitude=79.6467&current=temperature_2m,weather_code&daily=sunrise,sunset&timezone=Asia%2FKolkata&forecast_days=1'),fetch('https://air-quality-api.open-meteo.com/v1/air-quality?latitude=29.5892&longitude=79.6467&current=us_aqi&timezone=Asia%2FKolkata')]);if(!wr.ok)throw new Error('weather');const w=await wr.json(),a=ar.ok?await ar.json():null,n=Math.round(w.current.temperature_2m),sr=w.daily?.sunrise?.[0]?.split('T')[1]||'—',ss=w.daily?.sunset?.[0]?.split('T')[1]||'—';if($('#topTemp'))$('#topTemp').textContent=`${n}°C`;if($('#bigTemp'))$('#bigTemp').textContent=`${n}°C`;const sun=$$('.sunGrid b');if(sun[0])sun[0].textContent=sr;if(sun[1])sun[1].textContent=ss;const aqi=a?.current?.us_aqi;if($('.aqi'))$('.aqi').textContent=Number.isFinite(aqi)?`AQI ${Math.round(aqi)} · live`:'AQI · unavailable';if($('#weatherLine'))$('#weatherLine').textContent=`${n}°C · ${tr('sunrise')} ${sr} · ${tr('sunset')} ${ss}`;if($('#aqiLine'))$('#aqiLine').textContent=Number.isFinite(aqi)?`${tr('aqi')}: ${Math.round(aqi)} (US AQI)`:tr('weatherUnavailable')}catch{if($('.aqi'))$('.aqi').textContent='AQI · unavailable';if($('#weatherLine'))$('#weatherLine').textContent=tr('weatherUnavailable')}}
function localize(){$$('[data-local-key]').forEach(el=>{el.textContent=tr(el.dataset.localKey)});tick()}
document.addEventListener('DOMContentLoaded',()=>{localize();tick();liveWeather();setInterval(tick,1000);setInterval(liveWeather,10*60*1000);window.addEventListener('almora:language',localize)});
