const isAuth=document.body.classList.contains('authPage');
if(!isAuth){
let lang=localStorage.getItem('almoraLang')||'en';
const TEXT={
'Account':{hi:'खाता',kfy:'खाता'},'Businesses':{hi:'व्यवसाय',kfy:'कारोबार'},'Jobs':{hi:'रोज़गार',kfy:'रोजगार'},'Back to Almora AI':{hi:'अल्मोड़ा AI पर वापस',kfy:'अल्माड़ AI में वापस'},
'Work closer to home.':{hi:'घर के करीब काम करें।',kfy:'घर नजीक काम करौ।'},'Verified local opportunities only. Anyone can browse; signed-in employers can submit openings for moderation.':{hi:'केवल सत्यापित स्थानीय अवसर। कोई भी देख सकता है; लॉगिन किए नियोक्ता समीक्षा के लिए नौकरी भेज सकते हैं।',kfy:'केवल सत्यापित स्थानीय मौका। सब देख सकन; लॉगिन कारोबार समीक्षा खातिर नौकरी भेज सकन।'},'Post a vacancy.':{hi:'नौकरी पोस्ट करें।',kfy:'नौकरी पोस्ट करौ।'},'Submit for review':{hi:'समीक्षा के लिए भेजें',kfy:'जाँच खातिर भेजौ'},'No verified jobs yet':{hi:'अभी कोई सत्यापित नौकरी नहीं',kfy:'अभी सत्यापित नौकरी नि छन'},'Verified local vacancies will appear here after moderation.':{hi:'समीक्षा के बाद सत्यापित स्थानीय नौकरियाँ यहाँ दिखेंगी।',kfy:'जाँच बाद सत्यापित स्थानीय नौकरी यां दिखल।'},'Apply with my Almora profile':{hi:'मेरी अल्मोड़ा प्रोफ़ाइल से आवेदन करें',kfy:'म्यर अल्माड़ प्रोफाइल स आवेदन करौ'},'Application submitted.':{hi:'आवेदन भेज दिया गया।',kfy:'आवेदन भेजि दियो।'},'Profile saved.':{hi:'प्रोफ़ाइल सेव हो गई।',kfy:'प्रोफाइल बचि गै।'},
'Local businesses, visible to local people.':{hi:'स्थानीय व्यवसाय, स्थानीय लोगों के लिए दिखाई दें।',kfy:'स्थानीय कारोबार, स्थानीय लोगन लै साफ दिखौ।'},'Only approved business profiles are public. Signed-in owners can submit a listing for moderation.':{hi:'केवल स्वीकृत व्यवसाय प्रोफ़ाइल सार्वजनिक हैं। लॉगिन मालिक समीक्षा के लिए सूची भेज सकते हैं।',kfy:'केवल मंजूर कारोबार प्रोफाइल सार्वजनिक छन। लॉगिन मालिक जाँच खातिर सूची भेज सकन।'},'Add your business.':{hi:'अपना व्यवसाय जोड़ें।',kfy:'अपण कारोबार जोड़ौ।'},'Submit for verification':{hi:'सत्यापन के लिए भेजें',kfy:'जाँच खातिर भेजौ'},'No verified businesses yet':{hi:'अभी कोई सत्यापित व्यवसाय नहीं',kfy:'अभी सत्यापित कारोबार नि छन'},'Approved local businesses and services will appear here.':{hi:'स्वीकृत स्थानीय व्यवसाय और सेवाएँ यहाँ दिखेंगी।',kfy:'मंजूर स्थानीय कारोबार अर सेवा यां दिखल।'},'Business submitted for moderation.':{hi:'व्यवसाय समीक्षा के लिए भेजा गया।',kfy:'कारोबार जाँच खातिर भेजि दियो।'},
'Local help, without the phone-tree chaos.':{hi:'स्थानीय मदद, बिना फोन पर भटकने के।',kfy:'स्थानीय मदद, फोन-फोन घूमण बिना।'},'Request an electrician, plumber, cleaner, driver, home helper or local delivery. Requests stay private; verified providers can be matched as coverage grows.':{hi:'इलेक्ट्रीशियन, प्लंबर, सफाई, ड्राइवर, घरेलू मदद या स्थानीय डिलीवरी माँगें। अनुरोध निजी रहता है; कवरेज बढ़ने पर सत्यापित सेवा प्रदाता जोड़े जा सकते हैं।',kfy:'इलेक्ट्रीशियन, प्लंबर, सफाई, ड्राइवर, घर मदद या स्थानीय डिलीवरी माँगौ। अनुरोध निजी रहो; कवरेज बढ़ण पर सत्यापित सेवा द्याण वाल स्यूं मिलाण हो।'},'What do you need?':{hi:'आपको क्या चाहिए?',kfy:'तुम लै कै चाही?'},'Request details':{hi:'अनुरोध का विवरण',kfy:'अनुरोध को ब्योरो'},'Request local match':{hi:'स्थानीय मदद खोजें',kfy:'स्थानीय मदद खोजौ'},'Electrician':{hi:'इलेक्ट्रीशियन',kfy:'इलेक्ट्रीशियन'},'Plumber':{hi:'प्लंबर',kfy:'प्लंबर'},'Cleaner':{hi:'सफाई सहायता',kfy:'सफाई मदद'},'Driver':{hi:'ड्राइवर',kfy:'ड्राइवर'},'Home helper':{hi:'घरेलू मदद',kfy:'घर मदद'},'Medicine pickup / delivery':{hi:'दवा लाना / डिलीवरी',kfy:'दवाई लाण / डिलीवरी'},'Package / local delivery':{hi:'पैकेज / स्थानीय डिलीवरी',kfy:'पैकेज / स्थानीय डिलीवरी'},'Food pickup / delivery':{hi:'भोजन लाना / डिलीवरी',kfy:'खाण लाण / डिलीवरी'},'Request a local match.':{hi:'स्थानीय सहायता खोजें।',kfy:'स्थानीय मदद खोजौ।'},
'Your Almora profile.':{hi:'आपकी अल्मोड़ा प्रोफ़ाइल।',kfy:'तुमर अल्माड़ प्रोफाइल।'},'Keep a minimal local skills profile so jobs and useful local services can find you with your consent.':{hi:'अपनी सहमति से नौकरियों और उपयोगी स्थानीय सेवाओं के लिए न्यूनतम कौशल प्रोफ़ाइल रखें।',kfy:'अपणी सहमति स रोजगार अर स्थानीय सेवा खातिर कम-से-कम हुनर जानकारी राखौ।'},'Local skills profile':{hi:'स्थानीय कौशल प्रोफ़ाइल',kfy:'स्थानीय हुनर प्रोफाइल'},'Save profile':{hi:'प्रोफ़ाइल सेव करें',kfy:'प्रोफाइल बचौ'},'Sign out':{hi:'लॉग आउट',kfy:'बाहर जौ'},
'Sign in and create your profile first.':{hi:'पहले लॉगिन करके अपनी प्रोफ़ाइल बनाएँ।',kfy:'पैल लॉगिन करिक अपण प्रोफाइल बनौ।'},'Could not apply. Check your account and try again.':{hi:'आवेदन नहीं हो सका। अपना खाता जाँचें और फिर प्रयास करें।',kfy:'आवेदन नि भै। अपण खाता देखिक फेर कोशिश करौ।'},'Vacancy submitted for moderation.':{hi:'नौकरी समीक्षा के लिए भेजी गई।',kfy:'नौकरी जाँच खातिर भेजि दी।'}
};
const PLACEHOLDER={
'Role':{hi:'पद',kfy:'पद'},'Employer':{hi:'नियोक्ता',kfy:'काम द्याण वाल'},'Location':{hi:'स्थान',kfy:'ठौर'},'Pay range':{hi:'वेतन सीमा',kfy:'दाम / वेतन'},'Skills, hours, responsibilities':{hi:'कौशल, समय और जिम्मेदारियाँ',kfy:'हुनर, समय अर जिम्मेदारी'},'Business name':{hi:'व्यवसाय का नाम',kfy:'कारोबार को नाम'},'Category':{hi:'श्रेणी',kfy:'किसम'},'Public phone / email / website':{hi:'सार्वजनिक फोन / ईमेल / वेबसाइट',kfy:'सार्वजनिक फोन / ईमेल / वेबसाइट'},'What do you offer?':{hi:'आप क्या सेवा देते हैं?',kfy:'तुम कै सेवा द्यौ?'},'Locality / village':{hi:'क्षेत्र / गाँव',kfy:'इलाका / गौं'},'Describe the task':{hi:'काम का विवरण',kfy:'काम बतौ'},'Budget / expected price range (optional)':{hi:'बजट / अनुमानित कीमत (वैकल्पिक)',kfy:'बजट / दाम (चाहो त)'},'Display name':{hi:'दिखने वाला नाम',kfy:'दिखण नाम'},'Area / village':{hi:'क्षेत्र / गाँव',kfy:'इलाका / गौं'},'Skills, comma separated':{hi:'कौशल, कॉमा से अलग',kfy:'हुनर, कॉमा स अलग'},'Availability':{hi:'उपलब्धता',kfy:'कब उपलब्ध छौ'},'Short work summary':{hi:'काम का छोटा परिचय',kfy:'काम को छोटो परिचय'}
};
const originalText=new WeakMap();let busy=false;
function translated(base){const key=base.trim();if(!key)return base;const item=TEXT[key];if(!item||lang==='en')return base;const next=item[lang];if(!next)return base;const lead=base.match(/^\s*/)?.[0]||'',trail=base.match(/\s*$/)?.[0]||'';return lead+next+trail}
function translateTextNode(node){if(!originalText.has(node))originalText.set(node,node.nodeValue);node.nodeValue=translated(originalText.get(node))}
function translateTree(root=document.body){if(!root)return;busy=true;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&['SCRIPT','STYLE','NOSCRIPT'].includes(n.parentElement.tagName)?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});let n;while(n=walker.nextNode())translateTextNode(n);root.querySelectorAll?.('input[placeholder],textarea[placeholder]').forEach(el=>{if(!el.dataset.almoraPlaceholder)el.dataset.almoraPlaceholder=el.placeholder;const base=el.dataset.almoraPlaceholder,item=PLACEHOLDER[base];el.placeholder=lang==='en'||!item?.[lang]?base:item[lang]});busy=false}
function mountSwitch(){let btn=document.querySelector('#globalLangSwitch');if(!btn){btn=document.createElement('button');btn.id='globalLangSwitch';btn.className='globalThemeSwitch';btn.type='button';const host=document.querySelector('header nav')||document.querySelector('header');host?.appendChild(btn)}if(!btn)return;btn.textContent=lang==='en'?'EN':lang==='hi'?'हिं':'कुम';btn.onclick=()=>{const order=['en','hi','kfy'];lang=order[(order.indexOf(lang)+1)%3];localStorage.setItem('almoraLang',lang);document.documentElement.lang=lang==='kfy'?'kfy':lang;translateTree();mountSwitch()}}
function apply(){document.documentElement.lang=lang==='kfy'?'kfy':lang;translateTree();mountSwitch()}
const observer=new MutationObserver(records=>{if(busy)return;for(const record of records){for(const node of record.addedNodes){if(node.nodeType===Node.TEXT_NODE)translateTextNode(node);else if(node.nodeType===Node.ELEMENT_NODE)translateTree(node)}}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{apply();observer.observe(document.body,{childList:true,subtree:true})},{once:true});else{apply();observer.observe(document.body,{childList:true,subtree:true})}
}
