import'./page-theme.js';import{v7t,lang as getLang}from'./v7-locales.js';
const $=s=>document.querySelector(s);let all=[],shown=30,filter='all';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function bucket(p){const s=`${p.occupation} ${p.description}`.toLowerCase();if(/sport|badminton|cricket|mountain/.test(s))return'sports';if(/writer|poet|theatre|music|dance|artist|culture/.test(s))return'culture';if(/minister|civil|police|service|statesman|politic/.test(s))return'public';if(/science|engineer|innov|technology|entrepreneur|founder/.test(s))return'innovation';return'other'}
function meaningful(p){if(p.id==='mohit-pandey-almora-ai')return true;const text=`${p.connection||''} ${p.description||''} ${p.birthPlace||''}`.toLowerCase();return text.includes('almora')&&!/kumaon documented connection/.test(text)}
function applyCopy(){const hero=$('.atlasHero');hero.querySelector('span').textContent=v7t('peopleKicker');hero.querySelector('h1').textContent=v7t('peopleHero');hero.querySelectorAll('p')[0].textContent=v7t('peopleIntro');hero.querySelector('.atlasNote').textContent=getLang()==='hi'?'केवल वे सार्वजनिक व्यक्ति जिनका अल्मोड़ा से स्पष्ट और महत्वपूर्ण संबंध दस्तावेज़ित है।':getLang()==='kfy'?'केवल उई सार्वजनिक लोग जैंको अल्माड़ स्यूं साफ अर गहिरो संबंध दस्तावेज में छ।':'Only public figures with a documented, meaningful Almora connection are included.';$('#peopleSearch').placeholder=v7t('peopleSearch');$('#loadMore').textContent=v7t('loadMore');$('#atlasLang').textContent=getLang()==='hi'?'हिं':getLang()==='kfy'?'कुम':'EN'}
function render(){const q=$('#peopleSearch').value.toLowerCase().trim();const rows=all.filter(p=>meaningful(p)&&(filter==='all'||bucket(p)===filter)&&`${p.name} ${p.description} ${p.occupation} ${p.connection||''}`.toLowerCase().includes(q));const profileWord=getLang()==='hi'?'प्रोफ़ाइल':getLang()==='kfy'?'प्रोफाइल':'profiles';$('#peopleCount').textContent=`${rows.length} ${profileWord}`;$('#peopleGrid').innerHTML=rows.slice(0,shown).map(p=>`<article class="atlasPerson"><div class="personPortrait"><span class="personInitial">${esc((p.name||'?')[0])}</span>${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.remove()">`:''}</div><div class="personInfo"><small>${esc(p.occupation||bucket(p))}</small><h3>${esc(p.name)}</h3><p><b>${getLang()==='hi'?'अल्मोड़ा संबंध':getLang()==='kfy'?'अल्माड़ संबंध':'Almora connection'}:</b> ${esc(p.connection||'Explicit public-source connection')}</p><p>${esc(p.description||'')}</p><a href="${esc(p.url||'#')}" ${String(p.url||'').startsWith('http')?'target="_blank" rel="noopener"':''}>${esc(v7t('publicSource'))}</a></div></article>`).join('');$('#loadMore').hidden=rows.length<=shown}
function mountFilters(){const cats=[['all',v7t('allPeople')],['sports',getLang()==='hi'?'खेल':getLang()==='kfy'?'खेल':'Sports'],['culture',v7t('culture')],['public',v7t('publicService')],['innovation',v7t('innovation')],['other',v7t('more')]];$('#peopleFilters').innerHTML=cats.map(([k,l],i)=>`<button class="${i?'':'active'}" data-filter="${k}">${l}</button>`).join('');document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;shown=30;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));render()})}
async function init(){try{const r=await fetch('./data/people.json?ts='+Math.floor(Date.now()/3600000));const d=await r.json();all=d.people||[]}catch{all=[]}applyCopy();mountFilters();render();$('#peopleSearch').oninput=()=>{shown=30;render()};$('#loadMore').onclick=()=>{shown+=30;render()};const theme=$('#atlasTheme');theme.onclick=()=>{const next=document.documentElement.dataset.theme==='heritage'?'modern':'heritage';document.documentElement.dataset.theme=next;localStorage.setItem('almoraTheme',next);theme.textContent=`◐ ${next==='heritage'?'Heritage':'Modern'}`};theme.textContent=`◐ ${document.documentElement.dataset.theme==='heritage'?'Heritage':'Modern'}`;$('#atlasLang').onclick=()=>{const seq=['en','hi','kfy'],l=getLang(),next=seq[(seq.indexOf(l)+1)%3];localStorage.setItem('almoraLang',next);location.reload()}}
init();
