import'./v7.js';
import{directory,officialLinks,liveNotices,places,radio,droneVideos,mapsUrl}from'./home-data.js';
import planningArt from'../art/monkey-menace-planning.js';

const COPY={
 en:{fallback:'The live AI did not answer quickly enough, so I am showing grounded Almora options instead.',health:'Here are useful health pathways around Almora.',jobs:'Here are local job and skill pathways.',education:'Here are education, scholarship and access pathways.',tourism:'Here are places and travel options around Almora.',travel:'Here are route-planning options from Almora.',transport:'Here are transport and road options for Almora.',government:'Here are official public-service links.',water:'Here are Water Watch and utility-help options.',culture:'Here are Kumaoni culture and listening options.',wildlife:'Here is the Monkey Watch and humane wildlife-conflict workflow.',news:'Here are current high-value Almora and Uttarakhand updates.',people:'Here are public profiles with meaningful Almora ties.',integrations:'Here are external app links with honest local fallbacks.',hill:'Here is the Hill Life coordination flow for problems that span several services.',founder:'Here is the Almora.ai founder and project-support page.',default:'Here are useful Almora options for your request.'},
 hi:{fallback:'लाइव AI ने समय पर उत्तर नहीं दिया, इसलिए भरोसेमंद स्थानीय विकल्प दिखाए जा रहे हैं।',health:'अल्मोड़ा के उपयोगी स्वास्थ्य रास्ते यहाँ हैं।',jobs:'स्थानीय रोज़गार और कौशल के रास्ते यहाँ हैं।',education:'शिक्षा, छात्रवृत्ति और पहुँच के रास्ते यहाँ हैं।',tourism:'अल्मोड़ा के आसपास घूमने और यात्रा के विकल्प यहाँ हैं।',travel:'अल्मोड़ा से यात्रा योजना के विकल्प यहाँ हैं।',transport:'अल्मोड़ा के यातायात और सड़क विकल्प यहाँ हैं।',government:'आधिकारिक सार्वजनिक सेवा लिंक यहाँ हैं।',water:'वॉटर वॉच और पानी/उपयोगिता सहायता यहाँ है।',culture:'कुमाऊँनी संस्कृति और सुनने के विकल्प यहाँ हैं।',wildlife:'यहाँ मंकी वॉच और मानवीय वन्यजीव-संघर्ष सहायता है।',news:'अल्मोड़ा और उत्तराखण्ड की महत्वपूर्ण ताज़ा खबरें यहाँ हैं।',people:'अल्मोड़ा से सार्थक रूप से जुड़े सार्वजनिक व्यक्तित्व यहाँ हैं।',integrations:'बाहरी ऐप और उनके स्थानीय विकल्प यहाँ हैं।',hill:'कई सेवाओं से जुड़ी समस्या के लिए हिल लाइफ़ समन्वय यहाँ है।',founder:'यह अल्मोड़ा.ai के संस्थापक और प्रोजेक्ट-सपोर्ट का पेज है।',default:'आपके सवाल के लिए उपयोगी अल्मोड़ा विकल्प यहाँ हैं।'},
 kfy:{fallback:'लाइव AI ले टैम में जवाब नि दियो, तैले भरोसेमंद स्थानीय विकल्प दिख रौ छन।',health:'अल्माड़ का काम का इलाज बाट यां छन।',jobs:'स्थानीय रोजगार अर हुनर का बाट यां छन।',education:'पढ़ाई, छात्रवृत्ति अर पहुंच का बाट यां छन।',tourism:'अल्माड़ आसपास घूमण अर सफर का विकल्प यां छन।',travel:'अल्माड़ स्यूं सफर योजना का विकल्प यां छन।',transport:'अल्माड़ का सफर अर सड़क विकल्प यां छन।',government:'सरकारी सेवा का सही लिंक यां छन।',water:'पाणि वॉच अर पाणि/सुविधा मदद यां छ।',culture:'कुमाऊँनी संस्कृति अर सुनण का विकल्प यां छन।',wildlife:'यां मंकी वॉच अर जंगली जानवर की दिक्कत को सुरक्षित बाट छ।',news:'अल्माड़ अर उत्तराखण्ड की जरूरी ताजा खबर यां छन।',people:'अल्माड़ स्यूं गहिरो संबंध राखण सार्वजनिक लोग यां छन।',integrations:'बाहर का ऐप अर स्थानीय विकल्प यां छन।',hill:'कई सेवा स्यूं जुड़ दिक्कत खातिर हिल लाइफ समन्वय यां छ।',founder:'यो अल्मोड़ा.ai का संस्थापक अर प्रोजेक्ट सहयोग को पेज छ।',default:'तुमर सवाल खातिर काम का अल्माड़ विकल्प यां छन।'}
};
const cache={};async function data(name,fallback){if(cache[name])return cache[name];try{const r=await fetch(`./data/${name}?ts=${Math.floor(Date.now()/3600000)}`);if(!r.ok)throw 0;return cache[name]=await r.json()}catch{return fallback}}
function detect(q=''){const s=q.toLowerCase();if(/news|latest|politic|innovation|science|technology|education news|sports news|खबर|समाचार|राजनीति|विज्ञान/.test(s))return'news';if(/mohit pandey|founder|support almora|fund almora/.test(s))return'founder';if(/rapido|zomato|swiggy|redbus|irctc|delivery app|ride app/.test(s))return'integrations';if(/distance|how (do|can) i (go|reach)|route to|ranikhet|bageshwar|haldwani|delhi|dehradun|nainital|pithoragarh/.test(s))return'travel';if(/elderly|medicine pickup|school access|whole problem|multiple problems|hill life|घर मदद/.test(s))return'hill';if(/person|people|who is|famous|prominent|व्यक्ति|लोग|हस्ती/.test(s))return'people';if(/hospital|doctor|health|clinic|medicine|अस्पताल|इलाज/.test(s))return'health';if(/job|work|career|hire|employment|रोजगार|काम/.test(s))return'jobs';if(/school|student|college|scholarship|education|teacher|पढ़ाई|स्कूल|छात्रवृत्ति/.test(s))return'education';if(/water|supply|pressure|tanker|electricity|power|utility|पानी|पाणि|बिजली/.test(s))return'water';if(/bus|taxi|transport|road|traffic|route|सड़क|बस|टैक्सी/.test(s))return'transport';if(/government|scheme|certificate|office|ration|pension|सरकार|प्रमाण/.test(s))return'government';if(/culture|song|music|festival|kumaoni|गीत|संस्कृति/.test(s))return'culture';if(/monkey|wildlife|animal|leopard|boar|बंदर|जंगली/.test(s))return'wildlife';if(/tour|visit|trip|temple|trek|hotel|घूम|मंदिर/.test(s))return'tourism';return'default'}
function directoryCard(x,icon='⌘'){return{icon,title:x.name,eyebrow:x.trust==='official'?'Official':'Directory',description:x.area||'',image:'',actions:[...(x.phone?[{label:'Call',url:`tel:${x.phone}`}]:[]),{label:'Directions',url:mapsUrl(x.query||x.name)},{label:'Source',url:x.sourceUrl||mapsUrl(x.query||x.name)}]}}
const img={jobs:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=900&q=80',education:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80',water:'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?auto=format&fit=crop&w=900&q=80',road:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=900&q=80',news:'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=900&q=80'};
async function cardsFor(topic){
 if(topic==='health')return directory.filter(x=>x.category==='health').slice(0,3).map(x=>directoryCard(x,'❤️'));
 if(topic==='jobs')return[{icon:'💼',title:'Local jobs',eyebrow:'Opportunities',description:'Browse local vacancies and moderated employer submissions.',image:img.jobs,actions:[{label:'Open jobs',url:'./jobs.html'}]},{icon:'🏪',title:'Business hiring',eyebrow:'Employers',description:'Businesses can verify themselves and publish local opportunities.',image:'',actions:[{label:'Business access',url:'./business-login.html'}]}];
 if(topic==='education')return[{icon:'🎓',title:'Rural Education',eyebrow:'Access + learning',description:'School access, scholarships, connectivity and career pathways.',image:img.education,actions:[{label:'Open education engine',url:'./education-rural.html'}]},{icon:'💼',title:'Jobs & skills',eyebrow:'Career bridge',description:'Connect education and skills to nearby work.',image:img.jobs,actions:[{label:'Open jobs',url:'./jobs.html'}]}];
 if(topic==='water')return[{icon:'💧',title:'Water Watch',eyebrow:'Locality signals',description:'Report outage, low pressure, irregular timing or suspected quality issues.',image:img.water,actions:[{label:'Open Water Watch',url:'./water.html'},{label:'Report',action:'report'}]},{icon:'🏛️',title:'District public utilities',eyebrow:'Official',description:'Use the district public-utilities directory for official information.',image:'',actions:[{label:'Official source',url:'https://almora.nic.in/public-utilities/'}]}];
 if(topic==='transport')return[...directory.filter(x=>x.category==='transport').slice(0,2).map(x=>directoryCard(x,'🚌')),{icon:'🛣️',title:'Report a road issue',eyebrow:'Town report',description:'Share the broad location and what happened so it can be reviewed.',image:img.road,actions:[{label:'Report',action:'report'},{label:'Route planner',url:'./travel.html'}]}];
 if(topic==='travel'){const d=await data('routes.json',{routes:[]});return(d.routes||[]).slice(0,3).map(x=>({icon:'🗺️',title:`Almora → ${x.name}`,eyebrow:`≈ ${x.distanceKm} km · ${x.time}`,description:`Via ${x.via}. ${x.modes.join(', ')}.`,image:'',actions:[{label:'Live route',url:x.map},{label:'All routes',url:'./travel.html'}]}))}
 if(topic==='integrations'){const d=await data('integrations.json',{integrations:[]});return(d.integrations||[]).slice(0,3).map(x=>({icon:x.icon,title:x.name,eyebrow:x.status,description:x.fallback,image:'',actions:[{label:'Open service',url:x.url},{label:'App Bridge',url:'./integrations.html'}]}))}
 if(topic==='hill')return[{icon:'⛰️',title:'Hill Life Resolver',eyebrow:'Multi-agent coordination',description:'Coordinate health, roads, taxi, water, school and local-task steps in one flow.',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',actions:[{label:'Open resolver',url:'./hill-life.html'}]},{icon:'🤝',title:'Local task match',eyebrow:'Everyday help',description:'Request practical local help when one digital app is not enough.',image:'',actions:[{label:'Open services',url:'./services.html'}]}];
 if(topic==='founder')return[{icon:'👤',title:'Mohit Pandey',eyebrow:'Founder · Almora.ai',description:'Public founder profile, roadmap and transparent project-support page.',image:'https://avatars.githubusercontent.com/u/33383333?v=4',actions:[{label:'Open founder page',url:'./mohit-pandey.html'}]}];
 if(topic==='government')return officialLinks.slice(0,3).map(x=>({icon:'🏛️',title:x.label,eyebrow:'Official',description:x.detail,image:'',actions:[{label:'Official source',url:x.url}]}));
 if(topic==='culture')return[{icon:'🎵',title:radio[0].name,eyebrow:'Kumaoni music',description:radio[0].sub,image:radio[0].image,actions:[{label:'Listen',url:`https://www.youtube.com/results?search_query=${encodeURIComponent(radio[0].q)}`}]},{icon:'🎥',title:droneVideos[0]?.title||'Almora from above',eyebrow:'Video',description:droneVideos[0]?.note||'Aerial Almora views.',image:droneVideos[0]?`https://i.ytimg.com/vi/${droneVideos[0].youtubeId}/hqdefault.jpg`:'',actions:[{label:'Watch',url:droneVideos[0]?`https://www.youtube.com/watch?v=${droneVideos[0].youtubeId}`:'#culture'}]}];
 if(topic==='wildlife'){const m=await data('monkey-hotspots.json',{hotspots:[]});const top=[...(m.hotspots||[])].sort((a,b)=>b.activityIndex-a.activityIndex).slice(0,2);return[{icon:'🐒',title:'Monkey Watch activity map',eyebrow:'Reported activity',description:`${m.hotspots?.length||0} evidence-backed locality markers. Activity index is not a population census.`,image:planningArt,actions:[{label:'Open hotspot map',url:'./monkey.html'},{label:'Report incident',action:'report'}]},...top.map(h=>({icon:'📍',title:h.locality,eyebrow:`Activity ${h.activityIndex}/4`,description:`Published evidence dated ${h.evidenceDate}.`,image:'',actions:[{label:'Open map',url:'./monkey.html#hotmap'},{label:'Source',url:h.sourceUrl}]}))]}
 if(topic==='news'){const n=await data('live-news.json',{items:[]});return(n.items||[]).slice(0,3).map(x=>({icon:'◉',title:x.title,eyebrow:x.category,description:x.summary||`${x.source} · ${x.published||''}`,image:img.news,actions:[{label:'Read source',url:x.url},{label:'Almora Now',url:'#news'}]}))}
 if(topic==='people'){const p=await data('people.json',{people:[]});return(p.people||[]).filter(x=>x.featured).slice(0,3).map(x=>({icon:'👤',title:x.name,eyebrow:x.occupation||'People',description:x.connection||x.description,image:x.image||'',actions:[{label:'Public profile',url:x.url},{label:'People atlas',url:'./people.html'}]}))}
 return places.slice(0,3).map(x=>({icon:'🏔️',title:x.name,eyebrow:x.type||'Place',description:x.detail||'',image:x.image||'',actions:[{label:'Map',url:mapsUrl(`${x.name} Almora`)},{label:'Source',url:x.sourceUrl||'#places'}]}))
}
async function contextFor(topic,cards){const latest=await data('live-news.json',{items:[]}),agents=await data('agent-status.json',{agents:[]}),monkeys=topic==='wildlife'?await data('monkey-hotspots.json',{hotspots:[]}):{hotspots:[]};return['VERIFIED PUBLIC DATA / PRODUCT ROUTES:',...cards.map(c=>`${c.title}: ${c.description}`),...(topic==='transport'?liveNotices.slice(0,2).map(n=>`${n.title}: ${n.summary}`):[]),...(['news','default','government','jobs','education'].includes(topic)?(latest.items||[]).slice(0,6).map(n=>`LATEST ${n.category}: ${n.title} (${n.source})`):[]),...(topic==='wildlife'?(monkeys.hotspots||[]).slice(0,8).map(h=>`MONKEY REPORTED ACTIVITY ${h.activityIndex}/4: ${h.locality}; evidence ${h.evidenceDate}`):[]),`SYSTEM SIGNALS: ${(agents.agents||[]).filter(a=>a.signalCount).slice(0,5).map(a=>`${a.label}:${a.signalCount}`).join(', ')}`].join('\n')}
function withTimeout(p,ms=8000){return Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error('AI timeout')),ms))])}
async function askRich(query,lang='en'){const topic=detect(query),cards=await cardsFor(topic),key=topic==='hill'?'hill':topic,base={topic,agent:topic,cards,chips:cards.map(x=>x.eyebrow).filter(Boolean).slice(0,5),summary:COPY[lang]?.[key]||COPY.en[key]||COPY.en.default};try{const{askAlmoraAI,routeAgent}=await import('../../ai-client.js');const language=lang==='hi'?'natural Hindi':lang==='kfy'?'simple natural Almora-region Kumaoni in Devanagari; use plain Hindi rather than inventing uncertain Kumaoni words':'English';const prompt=`Respond in ${language}. Be warm, concise and practical. Use only grounded context for current facts. Never invent a road status, vacancy, official contact, monkey population, accusation, app availability or medical availability. Coordinate multiple Almora services when useful. USER: ${query}`;const response=await withTimeout(askAlmoraAI(prompt,await contextFor(topic,cards)));return{...base,agent:response.agent||routeAgent(query),summary:response.text,ai:true,model:response.model}}catch(e){console.warn('Almora AI fallback:',e);return{...base,summary:`${COPY[lang]?.fallback||COPY.en.fallback}\n\n${base.summary}`,ai:false}}}
export{askRich,detect};
