import'./page-theme.js';import{submitTownReport}from'./report-service.js';import{askRich}from'./rich-ai.js';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const lang=()=>localStorage.getItem('almoraLang')||'en';
const copy={en:{save:'Send for review',sending:'Sending…',saved:'Saved for review. Thank you.',offline:'Saved on this device; sync when connection returns.',ask:'Ask Almora AI',map:'Open live map',supportMissing:'UPI support will activate when the founder publishes the verified UPI handle.'},hi:{save:'समीक्षा के लिए भेजें',sending:'भेजा जा रहा है…',saved:'समीक्षा के लिए सुरक्षित हुआ। धन्यवाद।',offline:'इस डिवाइस पर सुरक्षित हुआ; कनेक्शन आने पर सिंक होगा।',ask:'अल्मोड़ा AI से पूछें',map:'लाइव नक्शा खोलें',supportMissing:'संस्थापक का सत्यापित UPI हैंडल प्रकाशित होने पर UPI सहायता सक्रिय होगी।'},kfy:{save:'जाँच खातिर भेजौ',sending:'भेजूं छ…',saved:'जाँच खातिर बचि गै। धन्यवाद।',offline:'ई डिवाइस में बचि गै; नेटवर्क ऐल त सिंक होल।',ask:'अल्माड़ AI लै पुछौ',map:'लाइव नक्शा खोलौ',supportMissing:'संस्थापक को सत्यापित UPI हैंडल प्रकाशित भै बाद UPI मदद चालू होल।'}};
async function mountReport(){const form=$('[data-town-report]');if(!form)return;form.onsubmit=async e=>{e.preventDefault();const category=form.dataset.category||$('select[name=category]',form)?.value||'Other',location=$('[name=location]',form)?.value.trim(),details=$('[name=details]',form)?.value.trim();if(!location||!details)return;const status=$('[data-status]',form);status.textContent=copy[lang()].sending;const r=await submitTownReport({category,location,description:details});status.textContent=r.synced?copy[lang()].saved:copy[lang()].offline}};
async function mountAsk(){const form=$('[data-ai-form]'),result=$('[data-ai-result]');if(!form||!result)return;form.onsubmit=async e=>{e.preventDefault();const q=$('input,textarea',form)?.value.trim();if(!q)return;result.innerHTML='<p>…</p>';const r=await askRich(q,lang());result.innerHTML=`<h3>${r.agent||'Almora AI'}</h3><p>${String(r.summary||'').replaceAll('<','&lt;')}</p><div class="infoRail">${(r.cards||[]).slice(0,3).map(c=>`<article><h3>${c.icon||'✦'} ${c.title}</h3><p>${c.description||''}</p>${(c.actions||[]).filter(a=>a.url).slice(0,2).map(a=>`<a href="${a.url}" ${String(a.url).startsWith('http')?'target="_blank" rel="noopener"':''}>${a.label} ↗</a>`).join(' ')}</article>`).join('')}</div>`}};
async function mountRoutes(){const root=$('[data-routes]');if(!root)return;try{const d=await fetch('./data/routes.json').then(r=>r.json());root.innerHTML=d.routes.map(x=>`<div class="routeRow"><b>Almora → ${x.name}</b><span>≈ ${x.distanceKm} km</span><span>${x.time}</span><small>${x.via}<br>${x.modes.join(' · ')}</small><a href="${x.map}" target="_blank" rel="noopener">${copy[lang()].map} ↗</a></div>`).join('')}catch{root.innerHTML='<p>Route data unavailable.</p>'}};
async function mountIntegrations(){const root=$('[data-integrations]');if(!root)return;try{const d=await fetch('./data/integrations.json').then(r=>r.json());root.innerHTML=d.integrations.map(x=>`<article class="integrationBox"><i>${x.icon}</i><b>${x.name}</b><small>${x.status}<br>${x.fallback}</small><a href="${x.url}" target="_blank" rel="noopener">Open official service ↗</a></article>`).join('')}catch{root.innerHTML='<p>Integration catalog unavailable.</p>'}};
const scenarios={
 medicine:[['🏥','Find care','Open health navigation and identify appropriate facility.'],['🛣️','Check access','Review road/transport conditions before leaving.'],['🚕','Arrange last mile','Use local taxi/shared-taxi options or available mobility apps.'],['📦','Pickup support','Use local task matching for medicine pickup when appropriate.']],
 school:[['🎓','School need','Capture the school, village and specific access/learning problem.'],['🚌','Transport','Check road and transport barriers affecting attendance.'],['📚','Learning fallback','Surface offline/online learning and scholarship resources.'],['🤝','Escalate','Create a reviewable education support case, not a public accusation.']],
 water:[['💧','Report locality','Record area, outage/pressure/quality issue and timing.'],['🧭','Cluster','Compare with nearby community reports as data grows.'],['🏛️','Official path','Surface the responsible public-utility contact/source.'],['📣','Status','Keep residents updated when a verified resolution is published.']],
 elderly:[['🧓','Need','Identify medicine, travel, bill/service or household-assistance need.'],['📍','Locality','Use broad locality rather than publishing a private home address.'],['🤝','Match','Route to trusted family/community/provider options where verified.'],['✅','Close loop','Confirm the task is completed instead of leaving it as a chat answer.']]
};
function mountResolver(){const root=$('[data-resolver]');if(!root)return;const buttons=$$('[data-scenario]'),out=$('[data-resolver-result]');const show=k=>{buttons.forEach(b=>b.classList.toggle('active',b.dataset.scenario===k));out.innerHTML=`<h3>${buttons.find(b=>b.dataset.scenario===k)?.textContent||'Hill Life Resolver'}</h3><div class="resolverSteps">${(scenarios[k]||scenarios.water).map(([i,b,p])=>`<div class="resolverStep"><span>${i}</span><div><b>${b}</b><p>${p}</p></div></div>`).join('')}</div>`};buttons.forEach(b=>b.onclick=()=>show(b.dataset.scenario));show(buttons[0]?.dataset.scenario||'water')}
async function mountFounder(){const host=$('[data-founder-support]');if(!host)return;let cfg={};try{cfg=await fetch('./data/founder.json').then(r=>r.json())}catch{};const id=String(cfg.upiId||'').trim();if(!id){host.innerHTML=`<p>${copy[lang()].supportMissing}</p><div class="upiState"><a href="${cfg.github||'https://github.com/coolcryptomaniac'}" target="_blank" rel="noopener">Follow the project on GitHub ↗</a></div>`;return}const uri=`upi://pay?pa=${encodeURIComponent(id)}&pn=${encodeURIComponent(cfg.name||'Mohit Pandey')}&tn=${encodeURIComponent('Support Almora.ai')}`;host.innerHTML=`<p>Support Almora.ai through UPI. Verify the payee name in your payment app before confirming.</p><div class="upiState"><code>${id}</code><button type="button" data-copy-upi>Copy UPI ID</button><a href="${uri}">Open UPI app</a><img alt="UPI QR" width="220" height="220" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&data=${encodeURIComponent(uri)}"></div>`;$('[data-copy-upi]',host).onclick=()=>navigator.clipboard?.writeText(id)}
mountReport();mountAsk();mountRoutes();mountIntegrations();mountResolver();mountFounder();
