const getLang=()=>localStorage.getItem('almoraLang')||'en';
const T={
'Home':{hi:'होम',kfy:'घर'},'Hill Life':{hi:'हिल लाइफ़',kfy:'हिल लाइफ'},'Water':{hi:'पानी',kfy:'पाणि'},'Education':{hi:'शिक्षा',kfy:'पढ़ाई'},'Travel':{hi:'यात्रा',kfy:'सफर'},'Apps':{hi:'ऐप्स',kfy:'ऐप'},'Jobs':{hi:'रोज़गार',kfy:'रोजगार'},'People':{hi:'लोग',kfy:'लोग'},'Local help':{hi:'स्थानीय मदद',kfy:'स्थानीय मदद'},
'WATER WATCH':{hi:'वॉटर वॉच',kfy:'पाणि वॉच'},'Make a local water problem visible.':{hi:'स्थानीय पानी की समस्या को दिखाई देने योग्य बनाइए।',kfy:'स्थानीय पाणि की दिक्कत साफ दिखौ।'},'Report a water issue':{hi:'पानी की समस्या रिपोर्ट करें',kfy:'पाणि की दिक्कत बतौ'},'Use a broad locality or landmark. Do not publish private household details.':{hi:'क्षेत्र या पहचान बताइए, निजी घर का विवरण सार्वजनिक न करें।',kfy:'इलाका या निशान बतौ, घर की निजी बात सार्वजनिक न करौ।'},'Locality / village':{hi:'क्षेत्र / गाँव',kfy:'इलाका / गौं'},'Issue type':{hi:'समस्या का प्रकार',kfy:'दिक्कत की किसम'},'What is happening?':{hi:'क्या हो रहा है?',kfy:'कै भै रौ छ?'},'Send for review':{hi:'समीक्षा के लिए भेजें',kfy:'जाँच खातिर भेजौ'},'How Water Watch helps':{hi:'वॉटर वॉच कैसे मदद करता है',kfy:'पाणि वॉच कसिक मदद करछ'},'Locality clustering':{hi:'क्षेत्र के अनुसार समूह',kfy:'इलाका हिसाब स्यूं समूह'},'Timing patterns':{hi:'समय का पैटर्न',kfy:'टैम को पैटर्न'},'Official path':{hi:'आधिकारिक रास्ता',kfy:'सरकारी बाट'},'Close the loop':{hi:'समाधान तक स्थिति ट्रैक करें',kfy:'समाधान तक हाल देखौ'},'Ask Water Watch':{hi:'वॉटर वॉच से पूछें',kfy:'पाणि वॉच लै पुछौ'},'Ask Almora AI':{hi:'अल्मोड़ा AI से पूछें',kfy:'अल्माड़ AI लै पुछौ'},
'RURAL EDUCATION':{hi:'ग्रामीण शिक्षा',kfy:'गौं की पढ़ाई'},'Keep learning reachable from the hills.':{hi:'पहाड़ से भी पढ़ाई पहुँच में रहे।',kfy:'पहाड़ में भी पढ़ाई पहुंच में राखौ।'},'What needs help?':{hi:'किस चीज़ में मदद चाहिए?',kfy:'कै चीज में मदद चाही?'},'Scholarships':{hi:'छात्रवृत्ति',kfy:'छात्रवृत्ति'},'School access':{hi:'स्कूल तक पहुँच',kfy:'स्कूल पहुंच'},'Digital learning':{hi:'डिजिटल पढ़ाई',kfy:'डिजिटल पढ़ाई'},'Career bridge':{hi:'करियर सेतु',kfy:'रोजगार को बाट'},'Report an education access problem':{hi:'शिक्षा पहुँच की समस्या रिपोर्ट करें',kfy:'पढ़ाई पहुंच की दिक्कत बतौ'},'Village / school area':{hi:'गाँव / स्कूल क्षेत्र',kfy:'गौं / स्कूल इलाका'},'Describe the barrier':{hi:'समस्या का विवरण',kfy:'रुकावट बतौ'},'Ask the education agent':{hi:'शिक्षा सहायक से पूछें',kfy:'पढ़ाई सहायक लै पुछौ'},
'ALMORA ROUTES':{hi:'अल्मोड़ा मार्ग',kfy:'अल्माड़ बाट'},'Know how far. Know how to go.':{hi:'दूरी भी जानें, रास्ता भी।',kfy:'कति दूर छ अर कसिक जां, दोनूं जाणौ।'},'From Almora':{hi:'अल्मोड़ा से',kfy:'अल्माड़ स्यूं'},'Ask a route question':{hi:'यात्रा के बारे में पूछें',kfy:'सफर की बात पुछौ'},'Open live map':{hi:'लाइव नक्शा खोलें',kfy:'लाइव नक्शा खोलौ'},
'APP BRIDGE':{hi:'ऐप ब्रिज',kfy:'ऐप ब्रिज'},'One place to jump into useful apps.':{hi:'उपयोगी ऐप खोलने की एक जगह।',kfy:'काम का ऐप खोलण की एक ठौर।'},'Connected services':{hi:'जुड़ी सेवाएँ',kfy:'जुड़ सेवा'},'Need a local alternative?':{hi:'स्थानीय विकल्प चाहिए?',kfy:'स्थानीय विकल्प चाही?'},'Local task match':{hi:'स्थानीय काम सहायता',kfy:'स्थानीय काम मदद'},'Local businesses':{hi:'स्थानीय व्यवसाय',kfy:'स्थानीय कारोबार'},'Intercity planner':{hi:'शहरों के बीच यात्रा',kfy:'नगर-नगर सफर'},'Hill Life Resolver':{hi:'हिल लाइफ़ समाधान',kfy:'हिल लाइफ समाधान'},'Open official service ↗':{hi:'आधिकारिक सेवा खोलें ↗',kfy:'आधिकारिक सेवा खोलौ ↗'},
'HILL LIFE COORDINATION ENGINE':{hi:'हिल लाइफ़ समन्वय इंजन',kfy:'हिल लाइफ समन्वय इंजन'},'Solve the whole problem, not one app at a time.':{hi:'पूरी समस्या सुलझाइए, एक-एक ऐप नहीं।',kfy:'पूरी दिक्कत सुलझौ, एक-एक ऐप नि।'},'Choose a real-life situation':{hi:'अपनी स्थिति चुनें',kfy:'अपणी स्थिति चुनौ'},'Medicine / hospital trip':{hi:'दवा / अस्पताल यात्रा',kfy:'दवाई / अस्पताल सफर'},'School access problem':{hi:'स्कूल पहुँच समस्या',kfy:'स्कूल पहुंच दिक्कत'},'Water outage':{hi:'पानी बंद',kfy:'पाणि बंद'},'Elderly person needs local help':{hi:'बुज़ुर्ग को स्थानीय मदद',kfy:'बुजुर्ग लै स्थानीय मदद'},'Describe your own situation':{hi:'अपनी स्थिति बताइए',kfy:'अपणी स्थिति बतौ'},'Coordinate with Almora AI':{hi:'अल्मोड़ा AI से समन्वय करें',kfy:'अल्माड़ AI स्यूं समन्वय करौ'},'Core local engines':{hi:'मुख्य स्थानीय इंजन',kfy:'मुख्य स्थानीय इंजन'},'Monkey Watch':{hi:'मंकी वॉच',kfy:'बंदर वॉच'},'Rural Education':{hi:'ग्रामीण शिक्षा',kfy:'गौं पढ़ाई'},'App Bridge':{hi:'ऐप ब्रिज',kfy:'ऐप ब्रिज'},
'FOUNDER · ALMORA.AI':{hi:'संस्थापक · ALMORA.AI',kfy:'संस्थापक · ALMORA.AI'},'Building Almora.ai as an open, AI-assisted local coordination layer for everyday hill-town life — services, culture, jobs, mobility, public information, wildlife conflict, water, education and community problem-solving.':{hi:'Almora.ai को पहाड़ी शहर के रोज़मर्रा जीवन के लिए खुले AI-सहायित स्थानीय समन्वय मंच के रूप में बनाया जा रहा है — सेवाएँ, संस्कृति, रोज़गार, यात्रा, सार्वजनिक जानकारी, वन्यजीव संघर्ष, पानी, शिक्षा और सामुदायिक समस्याएँ।',kfy:'Almora.ai लै पहाड़ी नगर की रोजमर्रा जिंदगी खातिर खुलो AI-सहायित स्थानीय समन्वय मंच बनूं छ — सेवा, संस्कृति, रोजगार, सफर, सार्वजनिक जानकारी, जंगली जानवर, पाणि, पढ़ाई अर समुदाय की दिक्कत।'},'Support Almora.ai':{hi:'Almora.ai का सहयोग करें',kfy:'Almora.ai लै सहयोग द्यौ'},'What support helps build':{hi:'सहयोग से क्या बनता है',kfy:'सहयोग स्यूं कै बनल'},'Transparency':{hi:'पारदर्शिता',kfy:'पारदर्शिता'},
'Open education engine':{hi:'शिक्षा इंजन खोलें',kfy:'पढ़ाई इंजन खोलौ'},'Open Water Watch':{hi:'वॉटर वॉच खोलें',kfy:'पाणि वॉच खोलौ'},'Open jobs':{hi:'रोज़गार खोलें',kfy:'रोजगार खोलौ'},'Open resolver':{hi:'समाधान खोलें',kfy:'समाधान खोलौ'},'Open services':{hi:'सेवाएँ खोलें',kfy:'सेवा खोलौ'},'Open service':{hi:'सेवा खोलें',kfy:'सेवा खोलौ'},'Full planner':{hi:'पूरा यात्रा प्लानर',kfy:'पूरो सफर प्लानर'}
};
const P={
'e.g. Khatyari, Dharanaula':{hi:'जैसे खत्याड़ी, धारानौला',kfy:'जै खत्याड़ी, धारानौला'},'When did it begin? Is the whole area affected?':{hi:'यह कब शुरू हुआ? क्या पूरा क्षेत्र प्रभावित है?',kfy:'यो कब शुरू भै? कै पूरो इलाका असर में छ?'},'Find scholarship and college options for a science student near Almora':{hi:'अल्मोड़ा के पास विज्ञान छात्र के लिए छात्रवृत्ति और कॉलेज विकल्प खोजें',kfy:'अल्माड़ नजीक विज्ञान छात्र खातिर छात्रवृत्ति अर कॉलेज विकल्प खोजौ'},'How should I go from Almora to Delhi tonight?':{hi:'आज रात अल्मोड़ा से दिल्ली कैसे जाऊँ?',kfy:'आज रात अल्माड़ स्यूं दिल्ली कसिक जौं?'},'What is happening?':{hi:'क्या हो रहा है?',kfy:'कै भै रौ छ?'}
};
const original=new WeakMap();let applying=false;
function translate(root=document){if(applying)return;applying=true;const l=getLang();const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){const p=n.parentElement;if(!p||['SCRIPT','STYLE','CODE'].includes(p.tagName))continue;const raw=original.get(n)??n.nodeValue;original.set(n,raw);const key=raw.trim();if(!key)continue;const hit=T[key]?.[l];if(hit)n.nodeValue=raw.replace(key,hit);else if(l==='en')n.nodeValue=raw}root.querySelectorAll?.('input[placeholder],textarea[placeholder]').forEach(el=>{const raw=el.dataset.superOriginalPlaceholder||el.placeholder;el.dataset.superOriginalPlaceholder=raw;el.placeholder=P[raw]?.[l]||raw});applying=false}
function init(){translate();document.addEventListener('click',e=>{if(e.target?.id==='globalLangSwitch')setTimeout(()=>translate(),80)},true);const obs=new MutationObserver(m=>{if(applying)return;for(const x of m)for(const n of x.addedNodes)if(n.nodeType===1)translate(n)});obs.observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',e=>{if(e.key==='almoraLang')translate()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
export{translate};
