import{mountHeroSlideshow}from'./hero-slideshow.js';import{mountLiveNews}from'./live-intelligence.js';import{initCultureTheme}from'./culture-theme.js';import{v7t}from'./v7-locales.js';
const style=document.createElement('link');style.rel='stylesheet';style.href='./src/styles/v7.css?v=7';style.id='almoraV7Style';if(!document.getElementById(style.id))document.head.appendChild(style);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let hotspotData=null,peopleData=null,agentData=null;
async function json(path,fallback){try{const r=await fetch(`${path}?ts=${Math.floor(Date.now()/3600000)}`);if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
function addNav(){const groups=[...document.querySelectorAll('.navGroup')];if(!groups.length)return;const first=groups[0],second=groups[1]||first;if(!document.querySelector('[href="./monkey.html"]'))first.insertAdjacentHTML('beforeend','<a class="navItem monkeyLaunch" href="./monkey.html"><i>🐒</i><span id="v7MonkeyNav"></span><em>MAP</em></a>');if(!document.querySelector('[href="./people.html"]'))second.insertAdjacentHTML('beforeend','<a class="navItem" href="./people.html"><i>👥</i><span id="v7PeopleNav"></span><span class="v7NavBadge">Atlas</span></a>');$('#v7MonkeyNav').textContent=v7t('monkeyWatch');$('#v7PeopleNav').textContent=v7t('peopleLabel')}
function renderMonkeyPreview(){const sec=$('.monkeyPreview');if(!sec||!hotspotData)return;const rows=[...(hotspotData.hotspots||[])].sort((a,b)=>b.activityIndex-a.activityIndex);const color={4:'#dc3325',3:'#f28a27',2:'#eabd2e',1:'#5d9e3f'};sec.innerHTML=`<div class="v7Head"><div><span class="v7SectionTitle">🐒 ${esc(v7t('monkeyWatch').toUpperCase())}</span><h2>${esc(v7t('monkeyHotspots'))}</h2><p>${esc(v7t('monkeyMethod'))}</p></div><a href="./monkey.html">${esc(v7t('openMonkey'))}</a></div><div class="hotspotStrip">${rows.slice(0,4).map(h=>`<a class="hotspotCell" href="./monkey.html#hotmap" style="text-decoration:none"><i style="color:${color[h.activityIndex]};background:${color[h.activityIndex]}"></i><b>${esc(h.locality)}</b><small>${h.activityIndex}/4 ${esc(v7t('reported'))}</small></a>`).join('')}</div><div class="hotspotScale"><span></span><b>${esc(v7t('lowHigh'))}</b></div>`}
async function mountMonkeyPreview(){const anchor=document.querySelector('#map')||document.querySelector('.bottomGrid');if(!anchor)return;hotspotData=await json('./data/monkey-hotspots.json',{hotspots:[]});const sec=document.createElement('section');sec.className='monkeyPreview';sec.id='monkey-watch';anchor.insertAdjacentElement('beforebegin',sec);renderMonkeyPreview()}
function renderPeoplePreview(){const sec=$('.peoplePreview');if(!sec||!peopleData)return;const rows=(peopleData.people||[]).filter(p=>p.featured).slice(0,5);sec.innerHTML=`<div class="v7Head"><div><span class="v7SectionTitle">👥 ${esc(v7t('peopleLabel').toUpperCase())}</span><h2>${esc(v7t('peopleTitle'))}</h2><p>${esc(peopleData.count||rows.length)} ${esc(v7t('peopleSub'))}</p></div><a href="./people.html">${esc(v7t('openPeople'))}</a></div><div class="peopleRail">${rows.map(p=>`<a class="miniPerson" href="${esc(p.url||'./people.html')}" target="_blank" rel="noopener"><div class="miniPortrait">${esc((p.name||'?')[0])}${p.image?`<img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy" onerror="this.remove()">`:''}</div><div><b>${esc(p.name)}</b><small>${esc(p.occupation||p.description||'')}</small></div></a>`).join('')}</div>`}
async function mountPeoplePreview(){const monkey=$('.monkeyPreview');if(!monkey)return;peopleData=await json('./data/people.json',{people:[]});const sec=document.createElement('section');sec.className='peoplePreview';sec.id='people';monkey.insertAdjacentElement('afterend',sec);const wrap=document.createElement('div');wrap.className='v7FeatureGrid';monkey.parentNode.insertBefore(wrap,monkey);wrap.append(monkey,sec);renderPeoplePreview()}
function renderAgentSignals(){const grid=$('#agentGrid');if(!grid||!agentData?.agents?.length)return;grid.parentElement.querySelectorAll('.agentSignalBar,.agentCollab').forEach(x=>x.remove());const bar=document.createElement('div');bar.className='agentSignalBar';bar.innerHTML=agentData.agents.filter(x=>x.signalCount).slice(0,6).map(a=>`<div class="agentSignal"><b>${esc(a.label)}</b><span>● ${a.signalCount} ${esc(v7t('currentSignals'))}</span></div>`).join('');grid.parentElement.appendChild(bar);if(agentData.collaborations?.length){const c=document.createElement('div');c.className='agentCollab';c.textContent=`${v7t('collaboration')}: ${agentData.collaborations.slice(0,3).map(x=>x.agents.join(' + ')).join(' · ')}`;grid.parentElement.appendChild(c)}}
async function mountAgentSignals(){agentData=await json('./data/agent-status.json',{agents:[],collaborations:[]});renderAgentSignals()}
function relocalize(){addNav();renderMonkeyPreview();renderPeoplePreview();renderAgentSignals()}
async function init(){addNav();initCultureTheme();mountHeroSlideshow();await Promise.allSettled([mountLiveNews(),mountMonkeyPreview(),mountAgentSignals()]);await mountPeoplePreview();window.addEventListener('almora:language',relocalize)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();