import{installRuntime,safeJSON}from'./app-runtime.js';installRuntime();
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const style=document.createElement('link');style.rel='stylesheet';style.href='./src/styles/v8.css?v=8.2';style.id='almoraV8Style';if(!document.getElementById(style.id))document.head.appendChild(style);
const lang=()=>localStorage.getItem('almoraLang')||'en';const L={en:{super:'Everyday problem solvers',superSub:'Purpose-built local engines for problems that cut across ordinary apps.',hill:'Hill Life Resolver',water:'Water Watch',edu:'Rural Education',apps:'App Bridge',routes:'From Almora',routeSub:'Approximate road planning with live-map handoff.',integrations:'Useful app bridge',integrationsSub:'Open external services, with local alternatives when coverage is weak.',founder:'Founder & support',founderSub:'See the builder, roadmap and transparent project-support page.',ready:'apps ready'},hi:{super:'रोज़मर्रा की समस्या समाधान',superSub:'ऐसी स्थानीय समस्याओं के लिए विशेष इंजन जो सामान्य ऐप्स से नहीं सुलझतीं।',hill:'हिल लाइफ़ समाधान',water:'वॉटर वॉच',edu:'ग्रामीण शिक्षा',apps:'ऐप ब्रिज',routes:'अल्मोड़ा से यात्रा',routeSub:'लाइव नक्शे के साथ अनुमानित सड़क योजना।',integrations:'उपयोगी ऐप ब्रिज',integrationsSub:'बाहरी सेवाएँ खोलें और कवरेज कम हो तो स्थानीय विकल्प देखें।',founder:'संस्थापक व सहयोग',founderSub:'निर्माता, रोडमैप और पारदर्शी प्रोजेक्ट-सपोर्ट पेज देखें।',ready:'ऐप तैयार'},kfy:{super:'रोजमर्रा दिक्कत समाधान',superSub:'ऐसी स्थानीय दिक्कत खातिर खास इंजन जैं सामान्य ऐप स्यूं नी सुलझन।',hill:'हिल लाइफ समाधान',water:'पाणि वॉच',edu:'गौं पढ़ाई',apps:'ऐप ब्रिज',routes:'अल्माड़ स्यूं सफर',routeSub:'लाइव नक्शा स्यूं अनुमानित सड़क योजना।',integrations:'काम का ऐप ब्रिज',integrationsSub:'बाहर का ऐप खोलौ, कवरेज कम हो त स्थानीय विकल्प देखौ।',founder:'संस्थापक अर सहयोग',founderSub:'निर्माता, रोडमैप अर पारदर्शी प्रोजेक्ट-सपोर्ट पेज देखौ।',ready:'ऐप तैयार'}};const t=k=>L[lang()]?.[k]||L.en[k];
async function get(path,fallback){const r=await safeJSON(path,{fallback,maxAge:60*60*1000,retries:1,timeout:5500,cacheKey:path});return r.value||fallback}
function nav(){const groups=[...document.querySelectorAll('.navGroup')];if(!groups.length)return;const first=groups[0],second=groups[1]||first;const links=[['./hill-life.html','⛰️','Hill Life'],['./water.html','💧','Water Watch'],['./education-rural.html','🎓','Rural Education'],['./travel.html','🗺️','Routes']];links.forEach(([href,icon,label])=>{if(!document.querySelector(`.navItem[href="${href}"]`))first.insertAdjacentHTML('beforeend',`<a class="navItem" href="${href}"><i>${icon}</i><span>${label}</span></a>`)});if(!document.querySelector('.navItem[href="./integrations.html"]'))second.insertAdjacentHTML('beforeend','<a class="navItem" href="./integrations.html"><i>📲</i><span>App Bridge</span></a>')}
async function superSection(){const anchor=$('#map')||$('.bottomGrid');if(!anchor||$('#superapp'))return;const apps=await get('./data/apps.json',{apps:[]});const sec=document.createElement('section');sec.className='section';sec.id='superapp';sec.innerHTML=`<div class="sectionHead"><div><h2>${esc(t('super'))}</h2><p>${esc(t('superSub'))}</p></div><span class="v8Badge">● ${apps.apps?.length||13} ${esc(t('ready'))}</span></div><div class="superGrid"><a class="superCard" href="./hill-life.html"><i>⛰️</i><b>${esc(t('hill'))}</b><small>Medicine + road + taxi + local task coordination in one flow.</small><strong>multi-agent</strong></a><a class="superCard" href="./water.html"><i>💧</i><b>${esc(t('water'))}</b><small>Outage, low pressure, timing and locality issue coordination.</small><strong>community signals</strong></a><a class="superCard" href="./education-rural.html"><i>🎓</i><b>${esc(t('edu'))}</b><small>School access, scholarships, digital learning and career bridge.</small><strong>rural access</strong></a><a class="superCard" href="./integrations.html"><i>📲</i><b>${esc(t('apps'))}</b><small>Mobility, food, bus, rail and maps — with honest local fallbacks.</small><strong>external + local</strong></a></div>`;anchor.insertAdjacentElement('beforebegin',sec)}
async function routes(){const anchor=$('#map')||$('.bottomGrid');if(!anchor||$('#routes-v8'))return;const d=await get('./data/routes.json',{routes:[]});const sec=document.createElement('section');sec.className='section';sec.id='routes-v8';sec.innerHTML=`<div class="sectionHead"><div><h2>${esc(t('routes'))}</h2><p>${esc(t('routeSub'))}</p></div><a class="v8Badge" href="./travel.html">Full planner →</a></div><div class="routeRail">${(d.routes||[]).map(x=>`<a class="routeCard" href="${x.map}" target="_blank" rel="noopener"><span>ALMORA →</span><b>${esc(x.name)}</b><small>≈ ${x.distanceKm} km · ${esc(x.time)}<br>${esc(x.via)}</small><em>Live map ↗</em></a>`).join('')}</div>`;anchor.insertAdjacentElement('beforebegin',sec)}
async function apps(){const anchor=$('#map')||$('.bottomGrid');if(!anchor||$('#apps-v8'))return;const d=await get('./data/integrations.json',{integrations:[]});const sec=document.createElement('section');sec.className='section';sec.id='apps-v8';sec.innerHTML=`<div class="sectionHead"><div><h2>${esc(t('integrations'))}</h2><p>${esc(t('integrationsSub'))}</p></div><a class="v8Badge" href="./integrations.html">Open hub →</a></div><div class="integrationRail">${(d.integrations||[]).map(x=>`<a class="integrationCard" href="${x.url}" target="_blank" rel="noopener"><i>${x.icon}</i><b>${esc(x.name)}</b><small>${esc(x.status)}</small></a>`).join('')}</div>`;anchor.insertAdjacentElement('beforebegin',sec)}
function hillBanner(){const home=$('.v7FeatureGrid')||$('#map');if(!home||$('.hillLifeBanner'))return;const b=document.createElement('div');b.className='hillLifeBanner';b.innerHTML=`<div><span class="v8Badge">COORDINATION ENGINE</span><h2>${esc(t('hill'))}</h2><p>One real problem may need health, transport, roads, water, education and local tasks together. Almora.ai resolves the sequence instead of sending you to disconnected apps.</p></div><a href="./hill-life.html">Try a situation →</a>`;home.insertAdjacentElement('beforebegin',b)}
function founder(){const access=$('.accessList')?.parentElement;if(!access||$('.founderMini'))return;const a=document.createElement('a');a.className='founderMini';a.href='./mohit-pandey.html';a.innerHTML=`<img src="https://avatars.githubusercontent.com/u/33383333?v=4" alt="Mohit Pandey"><div><b>${esc(t('founder'))}</b><small>${esc(t('founderSub'))}</small></div><span>Open →</span>`;access.appendChild(a)}
function relocalize(){['#superapp','#routes-v8','#apps-v8'].forEach(s=>$(s)?.remove());superSection();routes();apps()}
async function init(){nav();hillBanner();founder();await superSection();await Promise.allSettled([routes(),apps()]);window.addEventListener('almora:language',relocalize)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
